### ISSUE TITLE
valid function missing in kriging solver

### ISSUE THREAD

**Issue by exepulveda** [JuliaEarth/GeoStats.jl#100]
I'm not sure, but it seems the function valid() is missing.
It is used in KrigingEstimators/src/solvers/kriging.jl line 231

Apparently it should be defined in GeoStatsBase/src/data.jl but is not (on master).

**Comment by juliohm** [comment]
Sorry for the noise, I've removed the `valid` function in a [recent PR](https://github.com/JuliaEarth/GeoStatsBase.jl/pull/46) as part of the [plan](https://github.com/JuliaEarth/GeoStats.jl/issues/42) to improve the support for missing values. In previous versions of Julia we didn't have first-class support for `missing` and so I had introduced this `valid` function to return the all the coordinates and measurements with non-missing values. Nowadays, we can achieve the same result with something like:

```julia
inds = findall(!ismissing, sdata[:var])
dview = view(sdata, inds)
X, z = coordinates(dview), dview[:var]
```

Do you mind implementing this change in that PR as well?

**Comment by juliohm** [comment]
We are almost there refining this core API. These kinds of breaking changes shouldn't occur that often in the next releases :pray: It is been an interesting exercise to refine the project over time alongside the language.

I will close this issue, and we can continue the discussion in the PR :+1:

**Comment by exepulveda** [comment]
It could be better that you can do it because you know better the changes that are required. It could take me more time to understand what you implemented in "Introduce Variable".

**Comment by juliohm** [comment]
Of course, I will try to submit this change to the master branch by the end of the day.
