### ISSUE TITLE
More tests for local Kriging

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/GeoStats.jl#103]
@exepulveda I've noticed the current tests for local Kriging use a greedy neighborhood (ball with radius 100 on 100x100 grid). Do you think you could add more tests to stress the recent improvements to the solver?

**Comment by exepulveda** [comment]
Sure. I think we need to test better the estimations algorithms. Maybe wait for me until I finish the work to make a compatible results with GSLIB. That would be the ultimate test :-)

**Comment by exepulveda** [comment]
I could not reproduce results of local kriging of GSLIB.
It could be good to test with a well known dataset. For example, we could test using the dataset meuse from R package sp. 

Is there any clever way to apply verbosity for debugging purposes with the current code?

**Comment by juliohm** [comment]
It would be nice to reproduce the results with Global Kriging and Nearest Kriging first to make sure that these simpler variants are working as expected. I recall testing them in various cases and they produced reasonable results. The challenge with local Kriging as you know is that the estimation path becomes important, and different implementations, languages use different ordering of elements (e.g. row-major vs. column-major).

Have you tried the debugger in VS Code? It may be a bit slow, but if you have a small enough dataset to test, it could work. Another option is to try the Infiltrator.jl: https://github.com/JuliaDebug/Infiltrator.jl Finally, if you are using VS Code, and you are doing these tests in dev mode version of the packages, you can add print statements in the middle of the code and VS Code will trigger Revise.jl to recompile just this bit in the next execution.

Reproducing results is always a challenging exercise but definitely worth trying. We usually discover ways to improve the code. Thanks for the effort.

**Comment by juliohm** [comment]
Here is how you can launch the debugger in VS Code: https://youtu.be/IdhnP00Y1Ks?t=1007

**Comment by juliohm** [comment]
@exepulveda it would be also helpful if you can share in this issue the minimum working example you are trying to reproduce in both R and Julia. That would help us spot the differences more quickly. Also, the VS Code video above explains how we can work in a debugging session together in case any of us get stuck.

**Comment by exepulveda** [comment]
That is exactly what I will do. The good thing is that Kriging is deterministic, therefore any implementation should give the same results. 

It seems the VS Code debugger is quite slow. What is your opinion about including @debug statements into the code?

**Comment by juliohm** [comment]
> It seems the VS Code debugger is quite slow.

Try to check the "compiled mode" option in the debugger. It will avoid the slow JIT in the middle of the debugging session.

> What is your opinion about including @debug statements into the code?

I didn't consider it so far, but we can think about it carefully in the future if the VS Code debugger remains slow.

**Comment by exepulveda** [comment]
To start with, I want to reproduce the results of R package gstat:
```R
library(sp)
data(meuse)
coordinates(meuse) = ~x+y
data(meuse.grid)
gridded(meuse.grid) = ~x+y
m <- vgm(.59, "Sph", 874, .04)
# ordinary kriging:
x <- krige(log(zinc)~1, meuse, meuse.grid, model = m)
```
The variogram is for the log (natural) of zinc variable. The kriging system is OK. The sill 0.59 does not include the nugget effect of 0.04.

[meuse.txt](https://github.com/JuliaEarth/GeoStats.jl/files/5116678/meuse.txt)
[meuse_grid.txt](https://github.com/JuliaEarth/GeoStats.jl/files/5116679/meuse_grid.txt)

I hope I can do this this week

**Comment by exepulveda** [comment]
I could locally test global kriging and I got 💯 the same results. That is very good. I will continue with local kriging and then testing against GSLIB.

**Comment by juliohm** [comment]
Nice. It would be great if we could add some of these tests that you are running locally to the test suite so that we never miss them in future changes to the codebase. :100: Also, if you can share the Julia script equivalent to the code above, we can compare the syntax to see if there is place for improvement on our side.

Next step would be to try reproduce the nearest Kriging we have by setting an infinity radius neighborhood (large enough radius) in R gstat. I don't know if they have nearest Kriging, but that should reproduce the global Kriging results.

Back then, I wondered if this "formula notational" approach of R packages would be useful in the specification of the Kriging mean, but I was concerned that some students without stats background would struggle to get their head around formulas. In Julia, formulas are implemented via [StatsModels.jl](https://juliastats.org/StatsModels.jl/stable/formula/#Modeling-tabular-data-1). Another issue with formulas is that they were not designed initially for handling spatial coordinates as terms, so I don't know how the R package implements universal Kriging with formulas for instance. Are you aware of their adopted syntax for universal Kriging?

**Comment by exepulveda** [comment]
That is the idea. When I finish everything I will commit and PR :-)

gstat has knn as well. I dislike the "formula notational" but its could be nice for users coming from the R-side of the force.

**Comment by exepulveda** [comment]
I have a database (3D) to test which we can freely distribute!
This will be our case study:
3D EstimationProblem
  data:      6817 SpatialData{Float64,3}
  domain:    153076 PointSet{Float64,3}
  variables: bornite (Float64)

**Comment by juliohm** [comment]
@exepulveda did you have a chance to workout this test set?

**Comment by exepulveda** [comment]
I'm working on it. At the end of this week I could have something to show.

**Comment by exepulveda** [comment]
Preliminar results, GSLIB with not rotations and using homotopic variogram are OK.

I am using 89131 unknown locations to estimate.

GSLIB: 16s (Intel compiler)
JuliaEarth: 3s

The difference is good, but easy to explain. First GSLIB does rotation in every distance calculation, does not uses matrix factorisation and does not uses KDTree.

I'm happy with the preliminary results. Once I finish this I will PR the test.

**Comment by juliohm** [comment]
The timings are promising :+1: Though I remember I had difficulties when I tried to benchmark with GSLIB due to their monolithic codebase. Are these numbers considering IO?

Nevertheless, we should be doing well in terms of performance. Remember we are not even using multiple threads yet. I think the most important next step is to guarantee feature parity with GSLIB, including the rotations for example, and then make sure that we can reproduce well-known datasets.

Thanks for putting this benchmark together :100:

**Comment by exepulveda** [comment]
JuliaEarth: 3s without writting the output. But that will be minor. GSLIB does not use mutithreads as well. 
I'm in the condition to submit PR but I want to prepare something in agreement to avoid unnecessary iterations.
I'm working with a public synthetic dataset from a publisehd paper with some collegues. There are three files: (i) samples, (ii) a selection of locations to estimate with the GSLIB estimates and variances, (iii) the GSLIB parameter to reproduce the results.
What is the best way to upload everything?

**Comment by juliohm** [comment]
That is a good question. I wonder if we should aim for a well documented tutorial in GeoStatsTutorials instead? Given that it is hard to reproduce GSLIB without a precompiled binary, and that maintainers may not be willing to touch Fortran in the future, I think we could figure out an example that we could run whenever we update the Kriging code considerably. What do you think?

It would be nice to build a story around a known dataset, and if you could reproduce the results from your paper, that would be even nicer. A nice contribution to the list of tutorials for sure.

**Comment by juliohm** [comment]
Hi @exepulveda what do you think of this idea? Saving the files (i) and (ii) in the test set seems fine. I think the parameter file for GSLIB could go somewhere else like a notebook in GeoStatsTutorials where we could show the results side by side with current GeoStats.jl workflow assuming GSLIB executable is available and in the PATH.

**Comment by exepulveda** [comment]
It is the idea that I suggested time ago. I will submit a PR for the test because it is good including the two files. The test will have in a comment where the data were obtained from and how the GSLIB output was generated.

I will work in a notebook to show the case, but I need to test the rotations first.

**Comment by juliohm** [comment]
As I commented in that pull request, I realized that adding a test that depends so heavily on GSLIB, or any specific project for that matter, is problematic. I suggest to that we consider adding simpler smaller tests for the local Kriging method, like crafting a small grid by hand with specific measurements, and then writing down the expected results. That will be easier to maintain as a test in the project. And future contributors will be able to understand what is going on if the test fails.

**Comment by exepulveda** [comment]
It will not depend on GSLIB. It is like bootstrapping the results. We will be using GSLIB to internally validate LocalKriging. We arleady know that works, therefore, we can freeze our results and base the tests in our results (not GSLIB involved). Do you follow the idea?

**Comment by juliohm** [comment]
It makes sense to some extent, and I understand your viewpoint. But I am trying to say it is hard to decouple the expected theoretical result that we want to test from the side effects of an implementation detail. For simplicity, assume that we are writing a test for conditional Gaussian simulation, and that our implementation adopts a column-major order to visit the grid cells. Assume that some other project in some other language adopts row-major order instead. Both implementations are correct variations of the same theoretical idea, but their results cannot be compared. I know this it not the case with Kriging, but this is just to exemplify how hard it is to include another project, even indirectly, in the test suite.

Despite the issue above, there is also the issue that we cannot reason clearly about the test when it has hundreds of thousands of estimated cells. A good test is one where we can easily understand the expected results, and even obtain them by hand if possible. A good test also has the property that maintainers can quickly fix, update, ... and GSLIB is a barrier for maintainers.

Ideally we could write a small test example by hand to test the local Kriging results. Like a 10x10 grid with some data locations and some ball search that leaves cells without estimates etc. We could scale this example to more refined grids without losing the intuition about the expected results.

**Comment by exepulveda** [comment]
The example given does not help. Kriging is deterministic and the proposed test is not using a grid. I understand you point, but also beware that good tests do not only test simple calculations. I leave this to you. I will be focus on the notebook.

Regards

**Comment by juliohm** [comment]
Thanks, I will take care of it when I find some time.

**Comment by juliohm** [comment]
Given that tests are always important to have for any part of the project at any time, I will close this specific issue for now since no one is looking into it currently.
