### ISSUE TITLE
Refactor PointSet internal representation

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/GeoStats.jl#105]
Currently the PointSet is represented internally with a 2D matrix. Perhaps changing the internal representation to a vector of static vectors can give us an additional boost in performance in various algorithms.

**Comment by exepulveda** [comment]
Are you thinking about using StaticArray.jl?

For example:
`coords::Vector{SVector{N,T}}`

**Comment by juliohm** [comment]
Exactly. Given that most operations with the point set deal with "entire" points, we rarely need to slice the rows of the current 2D matrix. Most algorithms only require loop over columns. If all columns are static, we may get some additional compiler optimizations for free.

Would you like to tackle this one?

**Comment by exepulveda** [comment]
I would like take this one.

**Comment by exepulveda** [comment]
I will benchmark this case:

```
problem = EstimationProblem(data3D, pdomain, :bornita)
3D EstimationProblem
  data:      6817 SpatialData{Float64,3}
  domain:    153076 PointSet{Float64,3}
  variables: bornita (Float64)
```
The base scenario is:

```
for i in 1:10
  solution = @time solve(problem, solver)
end
  4.042634 seconds (3.67 M allocations: 11.620 GiB, 6.44% gc time)
  4.037391 seconds (3.67 M allocations: 11.620 GiB, 5.93% gc time)
  4.064429 seconds (3.67 M allocations: 11.620 GiB, 5.65% gc time)
  4.116754 seconds (3.67 M allocations: 11.620 GiB, 5.33% gc time)
  4.125295 seconds (3.67 M allocations: 11.620 GiB, 5.17% gc time)
  4.235886 seconds (3.67 M allocations: 11.620 GiB, 8.01% gc time)
  4.095777 seconds (3.67 M allocations: 11.620 GiB, 4.67% gc time)
  4.114237 seconds (3.67 M allocations: 11.620 GiB, 4.70% gc time)
  4.185361 seconds (3.67 M allocations: 11.620 GiB, 4.85% gc time)
  4.126609 seconds (3.67 M allocations: 11.620 GiB, 4.42% gc time)
```
Let's see how much we can reduce.

**Comment by juliohm** [comment]
Nice, you can also use the BenchmarkTools.jl package to get this time more accurately `@btime solve(problem, solver)`

**Comment by exepulveda** [comment]
With the new implementation:
```
for i in 1:10
         @time solve(problem, solver)
       end
  3.248977 seconds (3.21 M allocations: 3.808 GiB, 3.70% gc time)
  3.346375 seconds (3.21 M allocations: 3.808 GiB, 3.55% gc time)
  3.371415 seconds (3.21 M allocations: 3.808 GiB, 3.62% gc time)
  3.399316 seconds (3.21 M allocations: 3.808 GiB, 3.56% gc time)
  3.378670 seconds (3.21 M allocations: 3.808 GiB, 3.47% gc time)
  3.336218 seconds (3.21 M allocations: 3.808 GiB, 3.49% gc time)
  3.237753 seconds (3.21 M allocations: 3.808 GiB, 3.42% gc time)
  3.343776 seconds (3.21 M allocations: 3.808 GiB, 5.58% gc time)
  3.266192 seconds (3.21 M allocations: 3.808 GiB, 3.17% gc time)
  3.287763 seconds (3.21 M allocations: 3.808 GiB, 3.37% gc time)
```

**Comment by juliohm** [comment]
Nice, so it freed 1s approximately, and saved a considerable amount of memory allocation.

I spent the day again refactoring the codebase, I think it is almost there for the next generalization.

**Comment by exepulveda** [comment]
Yes, very nice. Should I send a PR for review?

**Comment by juliohm** [comment]
Please! :) I can review it tomorrow.

**Comment by juliohm** [comment]
And as a side comment, we can do a similar trick in a future PR to KrigingEstimators.jl to replace the internal representation of the X matrix by a vector of static vectors. This should speed up the Kriging solver as well.

**Comment by juliohm** [comment]
Fixed on master.
