### ISSUE TITLE
EmpiricalVariogram at lag 0

### ISSUE THREAD

**Issue by rmcaixeta** [JuliaEarth/GeoStats.jl#118]
Hi

I experienced an error when EmpiricalVariogram is calculated for lag = 0. It's not a common situation, it can be duplicated data problems in some cases. But also can be two half samples with different values that can be useful to estimate the nugget effect. Not sure how you prefer to handle it, but I'd include it to the first lag, something like that:

src/empirical.jl lines 192 and 240:
```julia
lag = h==0 ? 1 : ceil(Int, h / δh)
```

**Comment by juliohm** [comment]
Fixed.
