### ISSUE TITLE
Average lag distance

### ISSUE THREAD

**Issue by rmcaixeta** [JuliaEarth/GeoStats.jl#119]
Hi

Another suggestion that I think that would help variogram calculations. Would you consider using as the abscissa the average of `h` inside that lag instead of fixing the mid point between lag limits? Would help specially for large bins with irregular spaced data, pointing if the variogram vlaue is closer to upper or lower lag bound. It'd be necessary to add to the search_accum functions an extra `dist` array to accumulate `h` values and then average in the end like the other arrays. But not sure if having irregular spaced points could affect some of the others processes of the package, I did not try to make the changes locally yet but I can test and send a PR if you're ok with that.

By the way, I made some quick tests with foldxd, but foldxt gave better results indeed for partition variogram

**Comment by juliohm** [comment]
@rmcaixeta if you can also remove the `isnan` calls in your PR that would be great. We used to accept `NaN` as missing, but moving forward we will stick with `missing` only.

**Comment by juliohm** [comment]
Fixed.
