### ISSUE TITLE
Using nested variograms for kriging

### ISSUE THREAD

**Issue by rmcaixeta** [JuliaEarth/GeoStats.jl#121]
Hi

I've been making some tests of my workflows using GeoStats.jl. Got an error when I called a nested variogram (SumVariogram) for kriging:

```julia
ERROR: LoadError: type SumVariogram has no field distance
```

It'd be great to accept nested variograms for kriging and other solvers. Adding this line to `SumVariogram` seems to solve part of the problem (need validation yet):

```julia
distance(γ::SumVariogram) = distance(γ.γ₁)
```

This would be ok if the metric is the same for all the structures. But using GSLIB as reference, it'd be even better and more flexible if it's possible to consider different anisotropies per structure too, e.g Ellipsoidal([1.5,1.0], [0.0]) for 1st structure and Ellipsoidal([4.0,1.0], [0.0]) for 2nd structure. But not sure yet how's the best way to deal with that into the current code structure. If that's too difficult, I'll be happy enough with a partial solution assuming same metric for now

What do you think about it?

**Comment by juliohm** [comment]
That is a very good catch. I am impressed how we are not covering this use case in the tests. Do you have suggestions on how we could generalize the code to better deal with different anisotropies per structure?

It would be nice to fix this issue temporarily as you suggested with a new method for `distance` for both `SumVariogram` and `ScaledVariogram`. Would like to submit a PR? I'd be happy to review and merge. Appreciate the issues.

**Comment by juliohm** [comment]
Actually, it is strange that the Kriging code is asking for the distance of the variogram explicitly. Do you have a MWE? In theory each structure could have its own distance field, and the `SumVariogram` will call both in the `gamma(x, y)` method.

**Comment by rmcaixeta** [comment]
I'll copy here the example tomorrow, my machine is already off. But it was a simple Walker Lake 2d case with 2 structures and local neighborhood. I'll submit a PR in the weekend if that's the case for the simple fix. 

I'll think about how to deal with the anisotropy, still getting familiar with the project structure. My goal is to have solvers able to use non stationary covariances and other local anisotropy features until early next year (hopefully!)

**Comment by juliohm** [comment]
Awesome. I think the geometric anisotropy we currently have with this `distance` field may be useful already for the general case with multiple structures, but we can double check with your MWE. We can also brainstorm other ways to represent this anisotropy in the project to allow for more advanced workflows.

**Comment by rmcaixeta** [comment]
Great. Here a MWE using GeoStatsImages data:

```julia
using GeoStats, GeoStatsImages, Random

Random.seed!(1234)
D = geostatsimage("WalkerLake")
S = sample(D, 500)

Y = SphericalVariogram(sill=0.04, range=35., nugget=0.02) + SphericalVariogram(sill=0.045, range=60.)
Krig = solve(EstimationProblem(S, D, :Z), Kriging(:Z => (variogram=Y,maxneighbors=16)))
```

**Comment by juliohm** [comment]
Fixed in https://github.com/JuliaEarth/Variography.jl/commit/8107450b18a95d3777d71fcb877c72e4aa019cb6

For future reference, the second argument of the `EstimationProblem` should be `domain(D)` in your MWE. You may have issues downstream otherwise.

Thanks again for reporting the issue. A new release is being triggered with the fix.

**Comment by juliohm** [comment]
Also please share if you feel that the current design is limiting your workflow. Happy to brainstorm improvements.

**Comment by rmcaixeta** [comment]
Great, thanks @juliohm 
I like the current design so far, seems very flexible

Just to confirm. With that fix, it should be allowed to use different distance metric/anisotropy in nested structures, right?

**Comment by juliohm** [comment]
Yes, that is correct. You should be able to use different distance, one for each structure.
