### ISSUE TITLE
Turning Bands simulation.

### ISSUE THREAD

**Issue by exepulveda** [JuliaEarth/GeoStats.jl#125]
Hi all, part of my research now needs to run parallel simulations and one good choice is turning band (TB) method. Fortunately, I have Fortran code working and now I want to port this to JuliaEarth. Fortran code is very procedural and do-loop multi-dimensional arrays oriented. I am opening this issue for discussion in how to properly migrate the code that is GeoStats "compatible".

The first questions are:
TB uses number of lines to properly simulate the random field. Where should this parameter go?  For example:
```
solver = TurningBandsSim(
    :z => (variogram=GaussianVariogram(range=35.), lines=1000, neighborhood=BallNeighborhood(10.))
  )
```

TB simulates each nested variogram independently (they are additive). Is the nugget effect one nested variogram in Variogrphy.jl project?

Thanks for any advice.

**Comment by exepulveda** [comment]
I saw that you can have:
`vmodel = Spherical(nugget=0.2, sill=0.5, range=5.0) + Spherical(nugget=0.1, sill=1.0, range=70.0)`

I just wonder for the example above what is the total sill. I guess it should be 1.5 and the total nugget effect 0.3. Therefore each nested structure are:
Nugget: 0.3
Sill for the first spherical: 0.3
Sill for the second spherical: 0.9

Am I right?

**Comment by juliohm** [comment]
That's awesome @exepulveda. Looking forward to working out the details together. :100: 

> TB uses number of lines to properly simulate the random field. Where should this parameter go? For example:
> 
> ```
> solver = TurningBandsSim(
>     :z => (variogram=GaussianVariogram(range=35.), lines=1000, neighborhood=BallNeighborhood(10.))
>   )
> ```

The `lines` parameter makes sense to me. Is your question about the naming or about how to create such parameter within GeoStats.jl? I would call the solver `TurningBands` without the `Sim` suffix. The creation of solvers is documented here: https://juliaearth.github.io/GeoStats.jl/stable/contributing/solvers

> TB simulates each nested variogram independently (they are additive). Is the nugget effect one nested variogram in Variogrphy.jl project?

Currently we don't have a separate nugget effect type, but we could add a `NuggetEffect`, and write `NuggetEffect(0.3) + SphericalVariogram(sill=0.5)` for example. The nugget parameters in the current variogram types are currently part of the total sill, so when the user specifies `Spherical(sill=1.0, nugget=0.1)` the total sill is still `1.0`, makes sense? Some other projects refer to the sill parameter as a relative sill without taking the nugget into account. The proposed `NuggetEffect` would fit this approach.

Do you think it would be a good idea to share some references about the method in this issue so that we can can provide better reviews when you start implementing it? The reference I have in my hard drive is [Mantoglou & Wilson - The Turning Bands Method for Simulation of Random Fields using Line Generation by a Spectral Method](https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/WR018i005p01379). Are there other seminal papers we should be aware?

**Comment by juliohm** [comment]
You can query the exact value of nugget and sill of an additive model using the API in case you still have questions:

```julia
julia> using GeoStats

julia> γ1 = SphericalVariogram(nugget=0.2, sill=0.5, range=5.0)
SphericalVariogram{Float64,Distances.Euclidean}
  range: Float64 5.0
  sill: Float64 0.5
  nugget: Float64 0.2
  distance: Distances.Euclidean


julia> γ2 = SphericalVariogram(nugget=0.1, sill=1.0, range=70.0)
SphericalVariogram{Float64,Distances.Euclidean}
  range: Float64 70.0
  sill: Float64 1.0
  nugget: Float64 0.1
  distance: Distances.Euclidean


julia> γ = γ1 + 2γ2
SumVariogram{SphericalVariogram{Float64,Distances.Euclidean},ScaledVariogram{Float64,Distances.Euclidean,SphericalVariogram{Float64,Distances.Euclidean},Int64}}(SphericalVariogram{Float64,Distances.Euclidean}
  range: Float64 5.0
  sill: Float64 0.5
  nugget: Float64 0.2
  distance: Distances.Euclidean
, ScaledVariogram{Float64,Distances.Euclidean,SphericalVariogram{Float64,Distances.Euclidean},Int64}(2, SphericalVariogram{Float64,Distances.Euclidean}
  range: Float64 70.0
  sill: Float64 1.0
  nugget: Float64 0.1
  distance: Distances.Euclidean
))

julia> sill(γ)
2.5

julia> nugget(γ)
0.4

```

**Comment by exepulveda** [comment]
> That's awesome @exepulveda. Looking forward to working out the details together. 100
> 
> > TB uses number of lines to properly simulate the random field. Where should this parameter go? For example:
> > ```
> > solver = TurningBandsSim(
> >     :z => (variogram=GaussianVariogram(range=35.), lines=1000, neighborhood=BallNeighborhood(10.))
> >   )
> > ```
> 
> The `lines` parameter makes sense to me. Is your question about the naming or about how to create such parameter within GeoStats.jl? I would call the solver `TurningBands` without the `Sim` suffix. The creation of solvers is documented here: https://juliaearth.github.io/GeoStats.jl/stable/contributing/solvers

> 
> > TB simulates each nested variogram independently (they are additive). Is the nugget effect one nested variogram in Variogrphy.jl project?
> 
> Currently we don't have a separate nugget effect type, but we could add a `NuggetEffect`, and write `NuggetEffect(0.3) + SphericalVariogram(sill=0.5)` for example. The nugget parameters in the current variogram types are currently part of the total sill, so when the user specifies `Spherical(sill=1.0, nugget=0.1)` the total sill is still `1.0`, makes sense? Some other projects refer to the sill parameter as a relative sill without taking the nugget into account. The proposed `NuggetEffect` would fit this approach.
> 
> Do you think it would be a good idea to share some references about the method in this issue so that we can can provide better reviews when you start implementing it? The reference I have in my hard drive is [Mantoglou & Wilson - The Turning Bands Method for Simulation of Random Fields using Line Generation by a Spectral Method](https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/WR018i005p01379). Are there other seminal papers we should be aware?

The code I have in Fortran is the translation I did from the Matlab code of my colleague Xavier Emery' works:
Emery, X., & Lantuéjoul, C. (2006). TBSIM: A computer program for conditional simulation of three-dimensional Gaussian random fields via the turning bands method. Computers and Geosciences, 32(10), 1615–1628. https://doi.org/10.1016/j.cageo.2006.03.001

**Comment by exepulveda** [comment]
> You can query the exact value of nugget and sill of an additive model using the API in case you still have questions:
> 
> ```julia
> julia> using GeoStats
> 
> julia> γ₁ = SphericalVariogram(nugget=0.2, sill=0.5, range=5.0)
> SphericalVariogram{Float64,Distances.Euclidean}
>   range: Float64 5.0
>   sill: Float64 0.5
>   nugget: Float64 0.2
>   distance: Distances.Euclidean
> 
> 
> julia> γ₂ = SphericalVariogram(nugget=0.1, sill=1.0, range=70.0)
> SphericalVariogram{Float64,Distances.Euclidean}
>   range: Float64 70.0
>   sill: Float64 1.0
>   nugget: Float64 0.1
>   distance: Distances.Euclidean
> 
> 
> julia> γ = γ₁ + 2γ₂
> SumVariogram{SphericalVariogram{Float64,Distances.Euclidean},ScaledVariogram{Float64,Distances.Euclidean,SphericalVariogram{Float64,Distances.Euclidean},Int64}}(SphericalVariogram{Float64,Distances.Euclidean}
>   range: Float64 5.0
>   sill: Float64 0.5
>   nugget: Float64 0.2
>   distance: Distances.Euclidean
> , ScaledVariogram{Float64,Distances.Euclidean,SphericalVariogram{Float64,Distances.Euclidean},Int64}(2, SphericalVariogram{Float64,Distances.Euclidean}
>   range: Float64 70.0
>   sill: Float64 1.0
>   nugget: Float64 0.1
>   distance: Distances.Euclidean
> ))
> 
> julia> sill(γ)
> 2.5
> 
> julia> nugget(γ)
> 0.4
> ```

We may want to make available something like:
γ = NuggetEffect(0.2) + Spherical(sill=0.5, range=10.0) + Spherical(sill=0.8, range=70.0)

So SumVariogram may extend to manage an arbitrary number of nested structures. If that makes sense I can draft a PR to do so.

**Comment by juliohm** [comment]
That would be nice. We can simply add a `NuggetEffect <: Variogram` as another subtype of `Variogram`, and the rest of the behavior should follow automatically with sums and scalings. I will be happy to review the PR.

**Comment by rmcaixeta** [comment]
Nice one. It'll be great to have a good and fast opensource TBS!

**Comment by exepulveda** [comment]
Do you think that this enough?
```
"""
    NuggetEfect(n)

A pure nugget effect (random) variogram with nugget `n`
"""
@with_kw struct NuggetEfect{T, D} <: Variogram{T,D}
  nugget::T = 0.
  distance::D = Euclidean()
end
(γ::NuggetEfect)(h) = (h > 0) * γ.nugget
isstationary(::Type{<:NuggetEfect}) = true
```

**Comment by exepulveda** [comment]
Quick question: why float constant are 0. and not 0.0?

**Comment by juliohm** [comment]
That would be a good `NuggetEffect`, but we also need to specialize `sill(g::NuggetEffect) = g.nugget`, and `range(::NuggetEffect) = 0` so that it can be used anywhere like the other variogram models.

Regarding the `0.`, I think we could just write `0.0` or `zero(T)`. Same for the `1.`, we could just write `1.0` or `one(T)`. I had no particular reason to leave the 0 out of the literal. Feel free to include these changes in the PR :+1:

**Comment by exepulveda** [comment]
This version is almost OK
```
"""
    NuggetEfect(n)

A pure nugget effect (random) variogram with nugget `n`
"""
@with_kw struct NuggetEffect{T,D} <: Variogram{T,D}
  nugget::T = 0.0
  distance::D = Euclidean()
end
function NuggetEffect(n::T) where {T <: AbstractFloat}
  @assert n > 0 "Nugget effect should be greater than zero"
  NuggetEffect(nugget=n)
end

(γ::NuggetEffect{T,D})(h) where {T,D} = (h > 0) ? γ.nugget : zero(T)
Base.range(::NuggetEffect{T,D}) where {T,D} = zero(T)
sill(γ::NuggetEffect) = nugget(γ)
isstationary(::Type{<:NuggetEffect}) = true
```
Few problems:
In the tests I have:```

γ = NuggetEffect(0.2)
γ₁ = γ + GaussianVariogram(nugget=0.1, sill=0.8, range=50.0)
@test nugget(γ₁) = 0.3
```
which fails. 0.2 + 0.1 should be 0.3 but is actually ```
julia> 0.2 + 0.1
0.30000000000000004
```
Also because `NuggetEffect` does not have sill and range attributes, the fit function does not work. One easy but bad solution could be to include those attributes and not use them. Final solution should be modify the fit function to not assume somehow every structure has those attributes.

**Comment by juliohm** [comment]
I think you fixed the approximate comparison in https://github.com/JuliaEarth/Variography.jl/pull/31 already. Regarding the lack of sill and range attributes in the fit function, I think we should deal with this issue separately. We need to work on the fit function to generalize it to additive models and models with pure nugget. Can we do that in a separate PR? Thanks.

**Comment by exepulveda** [comment]
I see two options:

1. To keep those unnecessary attributes (sill and range) to let the test suite to pass and after the fitting is fixed, we can remove them.
1. Remove them now but the test suite will fail.

I'm more inclined for the first option.

**Comment by juliohm** [comment]
Tests are failing because you've added the nugget effect to test sets that aren't supposed to work currently. Fitting variograms is a different issue. Let's do things one step at a time. Can you please update the PR to remove the nugget effect from the fitting tests?

**Comment by juliohm** [comment]
Also keep in mind that this discussion we are having here about nugget effects is going to be lost after we close the issue, which is about Turning Bands. Let's try to organize our discussions carefully so that their record is available to future contributors.

The same holds for PRs. We need to define a scope for issues and PRs otherwise we won't be able to find the design decisions that were made in a future time, and the rationale behind these decisions.

**Comment by juliohm** [comment]
I am closing this issue for now because it contains a lot of information that is unrelated to the Turning Bands solver. We can open a separate issue when someone is actually free to implement this.
