### ISSUE TITLE
Extend cross-validations to EstimationProblems

### ISSUE THREAD

**Issue by rmcaixeta** [JuliaEarth/GeoStats.jl#128]
Opening this issue to extend cross validation methods for `EstimationProblem`

Looking quickly at the code, seems that they're currently restricted to `LearningProblem`. And it's apparently easy to extend them to `EstimationProblem`.

Or is there already some way to call an `EstimationProblem` as a `LearningProblem`?

**Comment by juliohm** [comment]
We used to have CV for estimation problems, but it got removed in the middle a major refactoring of the codebase. Please feel free to submit a PR, and we can review it together.

**Comment by juliohm** [comment]
@rmcaixeta we are almost there regarding this issue. I've refactored all cross-validatory methods and the code is much cleaner now. The next step consists of generalizing to estimation problems.

**Comment by juliohm** [comment]
Fixed on master 👍🏽
