### ISSUE TITLE
Migrate Tutorials to Pluto.jl

### ISSUE THREAD

**Issue by NitishGadangi** [JuliaEarth/GeoStats.jl#133]
**Description:**
Rewrite the current tutorials (which were written in Jupyter Notebook) in [Pluto.jl](https://github.com/fonsp/Pluto.jl) 

**Deliverables:**
- [x] Estimation problems
- [x] Variogram modeling
- [x] Anisotropic models
- [x] Directional variograms
- [x] Declustered statistics
- [x] Two-point statistics
- [x] Gaussian processes
- [x] Image quilting
- [x] Parallel simulation
- [x] Cookie-cutter

**Comment by juliohm** [comment]
Great to finally have the notebooks running on Pluto! They look much nicer now!
