### ISSUE TITLE
Metric trees and spheres

### ISSUE THREAD

**Issue by Mattriks** [JuliaEarth/GeoStats.jl#140]
In [these lines](https://github.com/JuliaEarth/GeoStatsBase.jl/blob/147ba93fe8b571faa0ee74c4c22ec9e335cf699e/src/neighborsearch/neighborhood.jl#L20-L21), a `BallNeighborhood` is passed to `KDTree`. KDTrees can only be used with "Minkowski" metrics, which won't work for a sphere. So a minimum change here might be as follows.  I use `Haversine` here just an example. Or is there another way in `GeoStatsBase` to do this for spherical grids?

```julia
module t

using DataFrames, NearestNeighbors, GeoStatsBase


function GeoStatsBase.NeighborhoodSearch(object::O, neigh::N) where {O,N}
  kdtree = if neigh isa BallNeighborhood
#    KDTree(coordinates(object), metric(neigh))
    BallTree(coordinates(object), metric(neigh))
  else
    nothing
  end
  NeighborhoodSearch{O,N,typeof(kdtree)}(object, neigh, kdtree)
end


function points(r::SpatialData, inds::Vector{Int})
    c1 = permutedims(coordinates(r))
    d1 = DataFrame(c1[inds, :], [:x, :y])
    d1.x += -360*(180.0.<d1.x)
    return d1
end
    
end


# Example

# Note longitude = 0 to 360
a = RegularGrid((360, 180), (0., -90.), (1., 1.))
r1 = georef((z=zeros(360*180),), a)

b = BallNeighborhood(500., Haversine(6371.0))
s = NeighborhoodSearch(r1, b)
 inds = search([0.,0.], s)
d1 = t.points(r1, inds)

plot(d1, x=:x, y=:y, Geom.point, Coord.cartesian(fixed=true))
```

![haversine](https://user-images.githubusercontent.com/18226881/101324994-2aa07580-38bf-11eb-896b-8cfb935f15ed.png)

**Comment by juliohm** [comment]
Hi @Mattriks thank you for opening the issue. We have a method for the general case [here](https://github.com/JuliaEarth/GeoStatsBase.jl/blob/147ba93fe8b571faa0ee74c4c22ec9e335cf699e/src/neighborsearch/neighborhood.jl#L29-L49) and a method for the special Minkowski case [here](https://github.com/JuliaEarth/GeoStatsBase.jl/blob/147ba93fe8b571faa0ee74c4c22ec9e335cf699e/src/neighborsearch/neighborhood.jl#L52-L66). Perhaps we should consider generalizing the tree object from KDTree to the BallTree or some other tree when the distance is not Minkowski as you suggested.

What about an additional if statement in the lines you highlighted that checks if the metric is Minkowski and then sets the tree to BallTree? Something like:

```julia
  tree = if neigh isa BallNeighborhood
    if metric(neigh) isa "MinkowskiMetric"
      KDTree(coordinates(object), metric(neigh))
    else
      BallTree(coordinates(object), metric(neigh))
  else
    nothing
  end
```

Would you like to submit a PR? :) The MinkowskiMetric type could be a union like we did [here](https://github.com/JuliaEarth/Variography.jl/blob/7783bf6d4e1839fcf1f20a34303248a585ddfb49/src/empirical.jl#L5-L8).

**Comment by juliohm** [comment]
Regarding the spherical coordinates issue, I am actively working on a new package that will be added as a dependency of GeoStats.jl soon in order to generalize the domain definitions to manifolds embedded in R^n (e.g. sphere, geoid): https://github.com/JuliaGeometry/Meshes.jl It is still work in progress, but I hope to start the transition next month after new years eve.

**Comment by Mattriks** [comment]
I'm happy to submit a PR (not sure how soon). `NeighborhoodSearch` with your MinkowskiMetric condition seems suitable to me.  I'll definitely have a look at Meshes.jl!

**Comment by juliohm** [comment]
Since we are loading NearestNeighbors.jl in GeoStatsBase.jl you can also access `NearestNeighbors.MinkowskiMetric` instead of redefining the union type yourself. Thanks for considering contributing to the project.

**Comment by Mattriks** [comment]
@juliohm I'm trying out the new GeoStatsBase/Meshes.  In the following example, what is the way now to extract the coordinates from `s`?. My use case is that the next line is a custom function where I'd like to just pass `s` and not `r1` (and in the custom function I particularly want to know what the extreme values of the coordinates are).

```julia
# d is a GeoData.jl GeoArray
r1 = georef(DataFrame(DimTable(d[Ti(1)])), (:Lon, :Lat))
s = NeighborhoodSearch(r1, NormBall(500., Haversine(6371.0)))
```

**Comment by juliohm** [comment]
Hi @Mattriks , I think you should be able to `inds = search(Point(x), s)`. Please reach out in Gitter or Zulip if it doesn't work still. This migration to use Meshes.jl has many breaking changes, unfortunately.

**Comment by Mattriks** [comment]
Hi @juliohm, no that's just the indices, I want the full coordinates of the grid, preferably just from `s`.

**Comment by juliohm** [comment]
Given an index `i` you can get the coordinates of the centroid of the i-th
element of the grid with `c = centroid(grid, i)`. This will be a Meshes.jl
`Point`. You can retrieve the coordinates as a Julia vector with
`coordinates(c)`, makes sense?

If you have some previous code that was working before the update, feel
free to share and I can try to update it.

The main difference now is that we have full geometries for each index `i`
as opposed to a single coordinates vector. In the case of a CartesianGrid
you get `grid[i]` as a `Quadrangle` from Meshes.jl.

Em dom., 7 de mar. de 2021 às 23:15, Mattriks <notifications@github.com>
escreveu:
