### ISSUE TITLE
`convert` to array

### ISSUE THREAD

**Issue by mauro3** [JuliaEarth/GeoStats.jl#147]
Should there be a convert to array function?
```
julia> convert(Matrix, georef((Z=[10sin(i/10) + j for i in 1:100, j in 1:200],)))
ERROR: MethodError: Cannot `convert` an object of type 
  SpatialData{RegularGrid{Float64,2},DataFrames.DataFrame} to an object of type 
  Array{T,2} where T
```

**Comment by juliohm** [comment]
Thank you @mauro3 for raising the issue. I am still not sure if we should provide an API to convert spatial data on regular grids to Julia arrays. I am trying to delay this core design decision until we have the new spatial domain infrastructure in place.

Meanwhile, you can currently do:

```julia
reshape(D[:Z], size(domain(D)))
```

to recover the data array with correct shape. The `domain(D)` returns the underlying regular grid, which has a `size` like a Julia array. Not all domains have a `size` (e.g. point sets).

I wonder what we should do when two or more variables are available? Should these be stacked as a 3rd dimension of the array? It is not clear to me how this cube representation would be useful to end users. Maybe we can figure out the use cases and find out if there is something else that is missing in the API.

**Comment by mauro3** [comment]
Thanks for the speedy reply.

> I wonder what we should do when two or more variables are available?

I don't think a stacked, 3d array would be useful.  I think requiring the field as an argument would be best (maybe defaulting to the first).  Something like:
```
convert2array(D, :z)
```

**Comment by juliohm** [comment]
What about a `toarray(D, :Z)` utility function? Many users have asked this question before so I think it makes sense to provide something while the other changes are not available yet. Mind working on a PR? :)

**Comment by mauro3** [comment]
Can do.  But that would go into GeoStatsBase, right?

**Comment by juliohm** [comment]
Yes, that would go in GeoStatsBase.jl 👍🏽
