### ISSUE TITLE
Improve GslibIO.jl to incorporate the GSLIB format for point set

### ISSUE THREAD

**Issue by exepulveda** [JuliaEarth/GeoStats.jl#151]
Currently GslibIO.jl can only read GSLIB file for regular grids, but not for a generic GSLIB file. Also, the current implementation of load_legacy function does not properly manage the case when the second line in any GSLIB file contains the number of variables and annotated grid specification.

A plan of action would be:

- [ ] Write a helper function, `paser_legacy`, that parses a generic GSLIB file and return the metadata (header, and variable names) and the parsed data.
- [ ] Write the unit test for `paser_legacy`.
- [ ] Adap existing `load_legacy` function to use `paser_legacy`. Note that this function only parses regular grids.
- [ ] Update unit tests for existing `load_legacy`.
- [ ] Add `load_legacy` for point set.
- [ ] Add unit test for this new `load_legacy` for point set.
- [ ] Implement `save_legacy` for both cases, regular grid and poit set.
- [ ] Add unit test for this new `save_legacy`.
- [ ] Update README.md.

**Comment by juliohm** [comment]
Thank you @exepulveda for writing up the plan, it helps a lot. Consider modifying the existing `load_legacy` with a minimum set of changes to parse and load at the same time the file contents, unless you are also planning to do something with the raw parsed version. The current `load_legacy` already does the parsing for regular grids, so perhaps a minimum amount of change to that function would be enough to cover the point set case.

In both cases, regular grid and point set, the parser/loader just needs to retrieve the table with spatial variables (table) and the spatial domain (domain) correctly and then a final call `georef(table, domain)` will handle the construction generically.

Please let me know when you have a first step finished, and I will be happy to review the code before moving forward with other changes to tests, and README.

**Comment by exepulveda** [comment]
It is going to be hard to keep existing `load_legacy` with minimum set of changes if we want to avoid code duplication. The proposed `parser_legacy` would used some code from `load_legacy`. Later, the two flavors of `load_legacy` (grid and point set) should use the new `parser_legacy`.

**Comment by juliohm** [comment]
Sounds good. Looking forward to reviewing a first version.

**Comment by juliohm** [comment]
Fixed in master! 🎉 Thanks for the contribution! The new release of GslibIO.jl should be coming out soon.
