### ISSUE TITLE
Expose Histogram options in EmpiricalHistogram

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/GeoStats.jl#153]
Currently the `EmpiricalHistogram` fits a normal `Histogram` using declustering weights. However, we need to expose other options of the `Histogram` to the end user such as the number of bins.

**Comment by juliohm** [comment]
@exepulveda would you like to try work on this one? It is a good exercise to improve Julia skills. Basically we need to forward the keyword arguments from the `fit(Histogram, args...; kwargs...)` to the `EmpiricalHistogram(sdata, v, s; kwargs...)`.

**Comment by cyborg1995** [comment]
@juliohm Hi! I would like to take this up!
Could you give please elaborate on the description and mention the prerequisites?
I'm new to GeoStats.jl but have experience with Julia.
Thanks!

**Comment by juliohm** [comment]
That is lovely @cyborg1995 ! I am more than happy to help you in the process.

In this issue we just want to forward all the keyword arguments of `fit(Histogram, ...)` to the GeoStats.jl `EmpiricalHistogram` function. Do you know how to do that already? In the affirmative case, you can `] dev GeoStatsBase` and submit the PR there.

If you are not familiar with the GitHub PR workflow, check this awesome repository: https://github.com/firstcontributions/first-contributions

Let me know if you have any questions. We are also on Gitter and Zulip for instant chat.

**Comment by cyborg1995** [comment]
Thanks for getting back!
I'm familiar with the GH workflow and I'll start working on this!

**Comment by juliohm** [comment]
Thanks again for the contribution @cyborg1995 ! The issue is now fixed in the master branch.

cc: @fnaghetini
