### ISSUE TITLE
Add new resource for potential contributors in the documentation

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/GeoStats.jl#155]
This post by Invenia is really welcome: https://invenia.github.io/blog/2021/01/29/contribute-open-source

Most people in Geosciences lack the necessary knowledge to contribute to open source software on GitHub, and the more we help the community in this process, the better. We need to update the developer guide and the contributing file to include this link.

**Comment by atreyamaj** [comment]
Hey!
While I was trying to update the guide (with the aforementioned link) and was looking for the .md file, I got a 404 error:

https://github.com/JuliaEarth/GeoStats.jl/blob/master/docs/src/developers.md

**Comment by atreyamaj** [comment]
Hey @juliohm !

I have submitted a PR for this issue. Please check it out!

https://github.com/JuliaEarth/GeoStats.jl/pull/163
