### ISSUE TITLE
Create a struct for EmpiricalHistogram

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/GeoStats.jl#157]
Currently `EmpiricalHistogram` is just a normal function. We need to create a struct like

```julia
struct EmpiricalHistogram
  hist::Histogram
end
```

and then provide outer constructors which are the functions already implemented. After that, we will be able to create a plot recipe for this new struct that should contain the contents of the `distplot1d` recipe.

A pull request would need to:

1. Create a new file `histograms.jl` with the struct and outer constructors
2. Add a corresponding `plotrecipes/histograms.jl` file with the plot recipe

@cyborg1995 would you like to tackle this one too? :)

**Comment by cyborg1995** [comment]
@juliohm yes, I would love to take this up!

**Comment by juliohm** [comment]
Thank you for another great contribution 💯
