### ISSUE TITLE
Add meta search with sectors and category constraints

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/GeoStats.jl#158]
Opening this issue to keep track of previous discussions in https://github.com/JuliaEarth/GeoStatsBase.jl/pull/70

@rmcaixeta perhaps you could copy/paste those illustrations here and explain briefly what exactly you are planning to implement when you find time.

**Comment by rmcaixeta** [comment]
OK. The goal is to implement two extra constraints in `BoundedSearch` function:
- Max neighbors per sector (e.g. max per octants)
- Max neighbors per category (e.g. max per drill hole)

![example](https://user-images.githubusercontent.com/8386288/107688512-7c31fb80-6c86-11eb-9ebd-fb6260af4870.png)

Both are common in mining softwares. They are used to avoid a clustered selection of neighbors and reduce string effects.
The idea is to implement them as keyword arguments (only used if explicitly called). Then it'd not affect current implementation of `BoundedSearch`. Something similar to:

```julia
BoundedSearch(method, maxneighbors=Inf; maxpercategory, maxpersector)
```

**Comment by juliohm** [comment]
Awesome, I think we can rename `BoundedSearch` to `FilteredSearch` to reflect the more advanced options 👌🏽

**Comment by juliohm** [comment]
Closing as too domain-specific with no actual demand from the broader community. We can reassess the feature in the future if someone is willing to submit PRs.
