### ISSUE TITLE
Migrate StratiGraphics.jl example notebook to GeoStatsTutorials

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/GeoStats.jl#159]
This is a simple issue for anyone interested in contributing to the project for the first time.

We need to convert this old Jupyter notebook of the StratiGraphics.jl solver to a Pluto notebook in our GeoStatsTutorials repository: https://nbviewer.jupyter.org/github/JuliaEarth/StratiGraphics.jl/blob/master/docs/Usage.ipynb

The notebook needs to be updated to replace the old solver name `SpecGaussSim` by `FFTGS` for example.

**Comment by juliohm** [comment]
@cyborg1995 this one is a nice one if you have experience in Pluto. Would you like to give it a try?

**Comment by cyborg1995** [comment]
I have only a little experience in Pluto.
Yes, I would love to give this a try! Would also get more experience with Pluto!

**Comment by juliohm** [comment]
Amazing. To accomplish this one:

1. Activate the folder `] activate GeoStatsTutorials/notebooks`
2. Add StratiGraphics to the dependencies `] add StratiGraphics`
3. Copy the format (e.g. header) of any other existing notebook in that folder
4. Migrate the content of the Jupyter notebook linked above to Pluto

Looking forward to help you in the process.
