### ISSUE TITLE
Add neighbors option to BlockPartition

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/GeoStats.jl#160]
The current implementation always computes the neighboring blocks, but we should add an option that disables this expensive calculation in large 3D block models. Additionally, the existing implementation of neighboring blocks can be improved for greater performance.

**Comment by atreyamaj** [comment]
Made a PR to Meshes.jl for this issue.
Please check it out:
https://github.com/JuliaGeometry/Meshes.jl/pull/60

**Comment by juliohm** [comment]
Fixed by @atreyamaj in master. Thanks!

**Comment by atreyamaj** [comment]
Thank you for helping me through the process!
