### ISSUE TITLE
Experimental Variogram parametrization

### ISSUE THREAD

**Issue by hameye** [JuliaEarth/GeoStats.jl#161]
Just saw this issue for block kriging and the aim to be usable in mining : https://github.com/JuliaEarth/GeoStats.jl/issues/40
Are you also considering to add new features or parameters customization in experimental variography such as:
- lag tolerance 
- dealing with geologist angle (azimuth/dip/pitch)
- angular tolerance 

Thanks,

Hadrien

**Comment by juliohm** [comment]
@hameye it depends on what parameters exactly you are referring to. The terminology changes from software to software, and the  current parametrization works fine in most applications we tried. Different parametrizations are possible if there is a good reason.

Check our paper Efficient Variography with Partition Variograms to understand our motivations. Most parametrizations in commercial software are incompatible with parallel implementations.

**Comment by juliohm** [comment]
Regarding the angles, we just need a function that converts from Cartesian to spherical coordinates for example. We currently have such function as `spheredir` but the mining industry doesn't follow the ISO standard for the angles so you may probably need to add a different convention as a separate function. We have a colleage at Datamine that did just that.

I will close the issue given that it is a question. Please feel free to ask more questions in our Gitter or Zulip channels.
