### ISSUE TITLE
Broken Documentation Link for 'Partitioning' 

### ISSUE THREAD

**Issue by atreyamaj** [JuliaEarth/GeoStats.jl#162]
The following link appears to be broken as it is giving a 404 error: 

https://juliaearth.github.io/GeoStats.jl/latest/operations/partitioning/

**Comment by juliohm** [comment]
Where is this link? Also, can you submit a PR directly to fix the issue?

**Comment by atreyamaj** [comment]
It came up on Google when I searched for "Geostats julia partitioning", although it seems like it does not exist in this repository. Please close the issue if it is unnecessary.

**Comment by juliohm** [comment]
Yes, please don't use Google for this.
