### ISSUE TITLE
Build issue in Julia 1.6.0-rc1

### ISSUE THREAD

**Issue by Mattriks** [JuliaEarth/GeoStats.jl#168]
I couldn't get GeoStatsBase v0.18+  to work on Julia 1.6.0-rc1.   The issue is the dependence on SplitApplyCombine.jl, which has a dependence on Indexing.jl. In a fresh env:

```julia
(@gsbase) pkg> add SplitApplyCombine
    Updating registry at `~\.julia\registries\General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
    Updating `~\.julia\environments\gsbase\Project.toml`
  [03a91e81] + SplitApplyCombine v1.1.4
    Updating `~\.julia\environments\gsbase\Manifest.toml`
  [85a47980] + Dictionaries v0.3.7
  [313cdc1a] + Indexing v1.1.0
  [03a91e81] + SplitApplyCombine v1.1.4
  [2a0f44e3] + Base64
  [b77e0a4c] + InteractiveUtils
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [9a3f8284] + Random
  [9e88b42a] + Serialization
  [8dfed614] + Test
0 dependencies successfully precompiled in 1 seconds (, 2 skipped during auto due to previous errors)
1 dependency errored

julia> using SplitApplyCombine
[ Info: Precompiling SplitApplyCombine [03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66]
ERROR: LoadError: ArgumentError: Package Indexing [313cdc1a-70c2-5d6a-ae34-0150d3930a38]
 is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.
```

Indexing.jl is an old package without a Project.toml, so instantiate doesn't help.

**Comment by juliohm** [comment]
Thank you for reporting the issue @Mattriks . I am about to release GeoStats.jl v0.22 which contains updates for the latest version of the language. I am using Julia v0.6-rc1 myself.

I am just waiting the documentation build to finish before triggering the registration bot.

**Comment by juliohm** [comment]
The PR should be merged soon in the General registry: https://github.com/JuliaRegistries/General/pull/31127

After that you can try to update the environment to get the latest release of all modules, including GeoStatsBase.jl.

Regarding the issue you had with `SplitApplyCombine.jl` I think it is better to report it there instead. It is unrelated to our efforts.

I will close the issue for now, but please feel free to comment here again if you still can't make things work after the update.

**Comment by Mattriks** [comment]
@juliohm - thanks.  Sorry I didn't mention above that SplitApplyCombine is a dependence of TypedTables (added in JuliaEarth/GeoStatsBase.jl#78). I'll have another go at getting it work.

**Comment by juliohm** [comment]
I see. We replaced the heavy DataFrames.jl by TypedTables.jl as our default
table type. It is unfortunate to learn that it has problematic
dependencies. Let me know if you still have problems. It should probably be
reported there too.

**Comment by Mattriks** [comment]
I have the same issue with GeoStatsBase.jl#master, in a fresh env.  I'm currently on a windows pc.

**Comment by juliohm** [comment]
It may be specific to Windows then. I'm on Linux and everything is working
fine on Julia v0.6-rc1.
