### ISSUE TITLE
Nootebooks need to be updated to reflect changes of v0.22

### ISSUE THREAD

**Issue by exepulveda** [JuliaEarth/GeoStats.jl#169]
I was checking the new v0.22 and some notebooks need to be updated, for example, in the notebook EstimationProblems.jl, there are two things to change:

1. RegularGrid (replaced by CartesianGrid).
2. The way to access the estimation results and the variance.

The point 1 is easy, just replacing RegularGrid by CartesianGrid in the code, but in the text I don't know what the new words are now the best.

The point 2 requires extra attention. The current code (line 115):
```
μ, σ² = solution[:precipitation]
```
which was very clear to work with, now needs extra changes, for example:

```
μ = solution[:precipitation]
σ² = solution[Symbol("precipitation-variance")]

```
but not sure if this approach is the clearest. (I know that some improvements are coming to used just `solution["precipitation-variance"]`). Maybe retrieving the estimation and variance with some specific function can be implemented, something like
```
μ = estimate(solution[:precipitation])
σ² = variance(solution[:precipitation])
```

The rest of the notebook works well (mostly plotting).

I also assume that other notebooks need to be updated as well.

**Comment by juliohm** [comment]
Thanks. In order to update the notebooks one needs to run `] up` in the notebooks folder to version v0.22 of the project, and then go notebook by notebook fixing the issues. The syntax `solution["Z-variance"]` should already be available.

**Comment by juliohm** [comment]
The solution to an estimation problem is now a simple geospatial data type so it makes sense to treat as such without special functions to access as suggested. Any geospatial data object should work with the syntax `D[:z]` or `D["z"]` whichever version is more convenient. Also, to preserve the shape `asrray` can be used instead.

**Comment by juliohm** [comment]
Fixed in GeoStatsTutorials.
