### ISSUE TITLE
Add Ripley's K test for point patterns

### ISSUE THREAD

**Issue by PeetoomHeida** [JuliaEarth/GeoStats.jl#173]
I am interested in contributing to this project. I was thinking of starting small by adding Ripley's K to the functions for point patterns. Does this fit in the project?

**Comment by juliohm** [comment]
Contributtons are very welcome. The PointPatterns.jl submodule is the
perfect place. :)

**Comment by juliohm** [comment]
@PeetoomHeida do you need some help to start with this?

**Comment by PeetoomHeida** [comment]
@juliohm No not quite yet. I am somewhat new to Julia, so just muddling along and testing different ways to get the function working. :)

**Comment by juliohm** [comment]
@PeetoomHeida any plans to work on this issue in the following months? Otherwise I will close it and let people reopen similar issues when they have time to submit PRs.

**Comment by PeetoomHeida** [comment]
Hey. Other things have come up and I don't have a lot of time to work on
it. Best to close it for now, if i make progress I will reopen and submit a
PR.

Cheers,
Isaac

**Comment by juliohm** [comment]
Thank you @PeetoomHeida for the heads up. Closing it for now.
