### ISSUE TITLE
SGS simulation does not work

### ISSUE THREAD

**Issue by anton-degterev** [JuliaEarth/GeoStats.jl#184]
After upgrading Julia to 1.6.1 and Geostats to 0.24.1, the SGS simulation fails. Returns the error "Balsearch not defined". The error is reproduced even if try to run the demo example from https://github.com/JuliaEarth/GeoSimulation.jl/blob/master/test/sgs.jl

Since the LUGS solver takes too long to work in typical practical situations, and the FFTGS solver only allows unconditional simulation, the loss of the ability to use SGS is quite sensitive

**Comment by juliohm** [comment]
Hi @anton-degterev , can you share the status of your environment?

```julia
] status
```

You probably have an old version of some of the modules in your system.

**Comment by juliohm** [comment]
Alternatively, you can add GeoStats.jl in a fresh environment to double check:

```julia
] activate @myenv
] add GeoStats
```

I will close the issue, feel free to re-open if the problem persists.

**Comment by juliohm** [comment]
I tried it locally and for some reason the Meshes.jl package is not in the latest version. Please try to `add Meshes@0.13` while we fix the issue in the dependency list.

**Comment by anton-degterev** [comment]
Here is the list of installed packages:

[336ed68f] CSV v0.8.4
[324d7699] CategoricalArrays v0.9.7
[d38c429a] Contour v0.5.7
[a93c6f00] DataFrames v1.1.1
[31c24e10] Distributions v0.25.0
[dcc97b0b] GeoStats v0.24.1
[916415d5] Images v0.24.1
[682c06a0] JSON v0.21.1
[91a5bcdd] Plots v1.13.2
[c3e4b0f8] Pluto v0.14.5
[7f904dfe] PlutoUI v0.7.9
[92933f4c] ProgressMeter v1.6.2
[6f49c342] RCall v0.13.11
[ce6b1742] RDatasets v0.7.5
[2913bbd2] StatsBase v0.33.8
[de0858da] Printf
[9a3f8284] Random
[10745b16] Statistics

I installed the package Meshes@0.13 but that didn't solve the problem. Now the package list looks like this:

  [336ed68f] CSV v0.8.4
  [324d7699] CategoricalArrays v0.9.7
  [d38c429a] Contour v0.5.7
  [a93c6f00] DataFrames v0.22.7
  [31c24e10] Distributions v0.24.18
  [dcc97b0b] GeoStats v0.21.1
  [916415d5] Images v0.24.1
  [682c06a0] JSON v0.21.1
  [eacbb407] Meshes v0.13.0
  [91a5bcdd] Plots v1.14.0
  [c3e4b0f8] Pluto v0.14.5
  [7f904dfe] PlutoUI v0.7.9
  [92933f4c] ProgressMeter v1.6.2
  [6f49c342] RCall v0.13.11
  [ce6b1742] RDatasets v0.7.5
  [2913bbd2] StatsBase v0.33.8
  [de0858da] Printf
  [9a3f8284] Random
  [10745b16] Statistics

Almost all of the packages in the list are needed to run the program I'm working on, so the idea of running in a new environment doesn't solve the problem, since almost all of these packages would have to be put there, too.

**Comment by juliohm** [comment]
Yes, I identified the issue already. and am currently triggering a set of patch releases. You should have access to GeoStats.jl v0.25 soon. Just waiting the bot in the General registry.

**Comment by juliohm** [comment]
The new release should be available in a couple of minutes: https://github.com/JuliaRegistries/General/pull/36799

Please let me know if the issue persists after the update. The command `] add GeoStats@0.25` should install the latest release after the PR above is merged.

**Comment by anton-degterev** [comment]
I updated the package to 0.25, but the problem is still reproducing. The error message: "UndefVarError: BallSearch not defined"

**Comment by juliohm** [comment]
Can you please share an example? I just tried in a clean environment and everything is working fine:

```julia
julia> using GeoStats

julia> p = SimulationProblem(CartesianGrid(10,10), :Z=>Float64, 3)
2D SimulationProblem (unconditional)
  domain:    10×10 CartesianGrid{2,Float64}
  variables: Z (Float64)
  N° reals:  3

julia> s = SGS(:Z=>(neighborhood=NormBall(1.),))
SGS
  └─Z
    └─variogram ⇨ GaussianVariogram{Float64, Euclidean}(1.0, 1.0, 0.0, Euclidean(0.0))
    └─neighborhood ⇨ NormBall{Float64}(1.0, Distances.Euclidean(0.0))
    └─minneighbors ⇨ 1
    └─maxneighbors ⇨ 10
    └─mapping ⇨ NearestMapping()


julia> solve(p, s)
2D Ensemble
  domain: 10×10 CartesianGrid{2,Float64}
  variables: Z
  N° reals:  3
```

**Comment by juliohm** [comment]
Please make sure you have the following versions of dependencies:

```julia
  [7472b188] GeoClustering v0.1.3
  [a4aa24f8] GeoEstimation v0.7.1
  [90c4468e] GeoLearning v0.1.3
  [220efe8a] GeoSimulation v0.3.4
  [dcc97b0b] GeoStats v0.25.0
  [323cb8eb] GeoStatsBase v0.21.4
  [d293930c] KrigingEstimators v0.7.4
  [eacbb407] Meshes v0.14.1
  [e61b41b6] PointPatterns v0.3.7
  [04a0146e] Variography v0.12.7
```

You can create a clean environment and add GeoStats.jl first. Then add the other packages you are using in your environment. That way GeoStats.jl and its dependencies will get priority in the version compat entries. You may have another package in your environment blocking indirect dependencies and causing you the trouble.

**Comment by anton-degterev** [comment]
I'm using this example for a test: https://github.com/JuliaEarth/GeoSimulation.jl/blob/master/test/sgs.jl

The current state of packages and dependencies obtained during the update:

  [a93c6f00] ↑ DataFrames v0.22.7 ⇒ v1.1.1
  [31c24e10] ↑ Distributions v0.24.18 ⇒ v0.25.1
  [dcc97b0b] ↑ GeoStats v0.21.1 ⇒ v0.25.0
  [7a955b69] + CircularArrays v1.2.0
  [a93c6f00] ↑ DataFrames v0.22.7 ⇒ v1.1.1
  [85a47980] + Dictionaries v0.3.8
  [31c24e10] ↑ Distributions v0.24.18 ⇒ v0.25.1
  [5789e2e9] ↑ FileIO v1.8.2 ⇒ v1.9.0
  [7472b188] + GeoClustering v0.1.3
  [a4aa24f8] ↑ GeoEstimation v0.4.2 ⇒ v0.7.1
  [90c4468e] + GeoLearning v0.1.3
  [220efe8a] ↑ GeoSimulation v0.1.0 ⇒ v0.3.4
  [dcc97b0b] ↑ GeoStats v0.21.1 ⇒ v0.25.0
  [323cb8eb] ↑ GeoStatsBase v0.17.1 ⇒ v0.21.4
  [313cdc1a] + Indexing v1.1.1
  [d293930c] ↑ KrigingEstimators v0.5.1 ⇒ v0.7.4
  [e80e1ace] ↑ MLJModelInterface v0.4.1 ⇒ v1.1.0
  [eacbb407] + Meshes v0.14.0
  [e1d29d7a] ↑ Missings v0.4.5 ⇒ v1.0.0
  [e61b41b6] ↑ PointPatterns v0.2.6 ⇒ v0.3.7
  [08abe8d2] ↑ PrettyTables v0.11.1 ⇒ v1.0.1
  [a2af1166] ↑ SortingAlgorithms v0.3.1 ⇒ v1.0.0
  [03a91e81] + SplitApplyCombine v1.1.4
  [64bff920] ↑ StatisticalTraits v0.1.1 ⇒ v1.1.0
  [ab02a1b2] + TableOperations v1.0.0
  [9d95f2ec] + TypedTables v1.2.4
  [04a0146e] ↑ Variography v0.10.4 ⇒ v0.12.7

Even if I make a new environment and add GeoStats.jl there first, when installing the other packages, they will automatically downgrade dependencies versions to compatible, so we will come to the same state.

Is there any way to detect an incompatible package?

**Comment by juliohm** [comment]
I just copied/pasted the example in a fresh environment and it worked fine:

```julia
julia> using GeoStats

julia> 𝒮 = georef((z=[1.,0.,1.],), [25. 50. 75.; 25. 75. 50.])
3 GeoData{2,Float64}
  variables
    └─z (Float64)
  domain: 3 PointSet{2,Float64}

julia> 𝒟 = CartesianGrid((100,100), (0.5,0.5), (1.0,1.0))
100×100 CartesianGrid{2,Float64}
  minimum: Point(0.5, 0.5)
  maximum: Point(100.5, 100.5)
  spacing: (1.0, 1.0)

julia> N = 3
3

julia> 𝒫₁ = SimulationProblem(𝒮, 𝒟, :z, N)
2D SimulationProblem (conditional)
  data:      3 GeoData{2,Float64}
  domain:    100×100 CartesianGrid{2,Float64}
  variables: z (Float64)
  N° reals:  3

julia> 𝒫₂ = SimulationProblem(𝒟, :z=>Float64, N)
2D SimulationProblem (unconditional)
  domain:    100×100 CartesianGrid{2,Float64}
  variables: z (Float64)
  N° reals:  3

julia> solver = SGS(:z => (variogram=SphericalVariogram(range=35.),
                             neighborhood=NormBall(30.)))
SGS
  └─z
    └─variogram ⇨ SphericalVariogram{Float64, Euclidean}(35.0, 1.0, 0.0, Euclidean(0.0))
    └─neighborhood ⇨ NormBall{Float64}(30.0, Distances.Euclidean(0.0))
    └─minneighbors ⇨ 1
    └─maxneighbors ⇨ 10
    └─mapping ⇨ NearestMapping()


julia> solve(𝒫₁, solver)
2D Ensemble
  domain: 100×100 CartesianGrid{2,Float64}
  variables: z
  N° reals:  3

julia> solve(𝒫₂, solver)
2D Ensemble
  domain: 100×100 CartesianGrid{2,Float64}
  variables: z
  N° reals:  3
```



> Even if I make a new environment and add GeoStats.jl there first, when installing the other packages, they will automatically downgrade dependencies versions to compatible, so we will come to the same state.
> 
> Is there any way to detect an incompatible package?

Good question. I think you can try to pin specific versions of the GeoStats.jl stack first and then when you try to add other packages an error will be thrown because of the downgrade. At that point you will have identified the conflicting package.

You can pin pin point the packages like this:

```julia
] add GeoClustering@0.1.3
```

See the list I shared above for all the dependencies.

**Comment by juliohm** [comment]
Just a correction, the way you pin packages is with `pin` instead of normal `add`.

**Comment by juliohm** [comment]
I will close the issue as it seems to be fixed now in a fresh environment. Feel free to reach out in the Gitter or Zulip channels for more help with setting up a working environment.

**Comment by anton-degterev** [comment]
The approach with pinning the version worked. Surprisingly, after updating the rest of the packages, no one swore, everyone accepted GeoClustering the desired version without any objections. The way the package manager handles dependencies is sometimes beyond understanding. After the restart, everything worked, so the problem is closed. Thanks!
