### ISSUE TITLE
Add glossary section in the documentation

### ISSUE THREAD

**Issue by Datseris** [JuliaEarth/GeoStats.jl#185]
For a newcomer like myself it would be very useful to know something about what `data` and `var1` means in the variogram functions

![image](https://user-images.githubusercontent.com/19669089/120384017-e9e16080-c325-11eb-8637-717e93f608aa.png)

If the desire is to not replicate information (which I completely agree with), then the functions should refernce the part of the docs that "what data is" is defined. I assume that `data = georef(....)` ? Then you could say that `data` is the ooutput of [`georef`](`@ref`).

Furthermore is `var1` the actual array data of the field I am interested in, or is it just an index for `data`, as `georef` already contains all the variables.?

**Comment by juliohm** [comment]
Fully agree. You are correct that data is the result of georef. Would you mind submitting a PR with proposed improvements? :)

**Comment by Datseris** [comment]
Sure thing! Tell also what `var`s should be and will include it!

**Comment by juliohm** [comment]
var is a Symbol representing the variable of interest that is stored inside the data.

**Comment by juliohm** [comment]
As discussed in the other issue/pr, a more general solution to this problem will involve adding a glossary to the documentation with elaborated definitions of the terms used across all docstrings of the project. There are too many and repeating the definitions in each can lead to outdated documentation very quickly.
