### ISSUE TITLE
Add docstring of values(variogram) to documentation

### ISSUE THREAD

**Issue by Datseris** [JuliaEarth/GeoStats.jl#186]
At the moment, looking at the doc page of Variograms, it seems like the only way to analyze Variograms is via the Plots.jl package. But I would much rather obtain the actual values that are plotted. How do I obtain:

1. Values of h axis
2. Values of γ(h)
3. Bin values b(h)

? I don't use Plots.jl and I see no mention in the documentation page on how to obtain these values. The display method of the variogram also does not give any hints.

```
julia> γ
EmpiricalVariogram
  abscissa: (0.05774133395425718, 3.0630528372500483)
  ordinate: (0.0, 0.09331917394861378)
  N° pairs: 176715
```

**Comment by juliohm** [comment]
You can get the values with `x, y, n = values(γ)`. Appreciate if you can add the docstring of the values function to the documentation somewhere. Thanks for sharing the issue. Also feel free to join our community channels in either gitter or zulip for these quick questions.

**Comment by juliohm** [comment]
Fixed on master.
