### ISSUE TITLE
Algorithms

### ISSUE THREAD

**Issue by omarbenites** [JuliaEarth/GeoStats.jl#188]
Hi @juliohm 

FOA, congrats on the amazing job in the development of this package!
I'm starting on the topic of geostatistics and trying to understand some of the methods (ex. empirical/theoretical variograms, Kringing, etc) and I observe you implemented quite well in Julia. For this reason, I'd like to ask you from Which reference or bibliography do you implemented all these methods and algorithms?. Maybe you have some information about it, and I'd really appreciate it if you share it.

Thanks in advance, and keep it up!

**Comment by juliohm** [comment]
Hi @omarbenites , thank you for the kind words. There are good books on geostatistics covering variography concepts. The algorithm we implemented is described in our paper [Efficient variography with partition variograms](https://www.sciencedirect.com/science/article/pii/S0098300419302936). I would start there and then follow the references.

Also, feel free to join our community channels for future questions. The GitHub issues are reserved for issues with the code and feature requests.

Best,
