### ISSUE TITLE
Error estimation by DensityRatioValidation

### ISSUE THREAD

**Issue by immaryw** [JuliaEarth/GeoStats.jl#192]
Hi, there! I'm trying to understand the idea behind DensityRatioValidation. I'm curious about how it is a less biased error estimator compared with k-fold cross-validation when covariate shift happens. 

![image](https://user-images.githubusercontent.com/17716760/128668852-5cbfda02-cd03-4e1f-a8f5-35ddf3d5d961.png)

As my terrible drawing :( shows, density ratio(weight) should be very small for most training data if Ptrain and Ptest overlaps slightly and most or all training data are sampled outside of Ptest1 and Ptest2, respectively. I also copied the equations from the paper "Covariate Shift Adaptation by Importance Weighted Cross Validation" (https://www.jmlr.org/papers/volume8/sugiyama07a/sugiyama07a.pdf), DRV should be smaller than KFCV. As we know standard k-fold cv always underestimates true error under covariate shift, and DRV is even smaller than KFCV. How DRV address covariate shift?

I may be wrong... I would appreciate if someone can help!!!

**Comment by juliohm** [comment]
Hi Jing Wang, the importance-weighted variants of cross-validation are derived assuming that the test distribution is within the train distribution. These cases where the overlap is very small aren't solved in the literature, they require specific knowledge from the problem at hand to overcome.

Also, notice that the GitHub issue tracker is for reporting issues or feature requests. Please use the Gitter or Zulip channels to ask questions in the future.

Best,
