### ISSUE TITLE
No `asarray` method for `Ensemble`

### ISSUE THREAD

**Issue by mauro3** [JuliaEarth/GeoStats.jl#193]
The title says it all.  As a work-around I have
```
asarray_(d::Ensemble, field) = reshape(d.reals[field][1], d.domain.dims)
```
Which works for my case but is probably not universal.

**Comment by juliohm** [comment]
What is the expected shape/result? An ensemble is a collection of geospatial data. You can do `asarray(d[1], :z)` to get the first realization in the ensemble as an array.

**Comment by mauro3** [comment]
Ah, ok, sorry for the noise.  I guess a better error message could be helpful.
