### ISSUE TITLE
How to run GeoStats.jl-example

### ISSUE THREAD

**Issue by StefanPofahl** [JuliaEarth/GeoStats.jl#203]
Hi,
how do I run your example, published in your project information:

The error-essage that I receive is:
`LoadError: AssertionError: invalid coordinates for table
in expression starting at C:\data\julia\scripts\GeoData\Test_GeoData.jl:12`

The content of "data.csv" is:
`   x,    y,       station,        precip`
`25.0, 25.0,     palo alto,           1.0`
`50.0, 75.0,  redwood city,           0.0`
`75.0, 50.0, mountain view,           1.0`
Julia v1.6.4

**Comment by juliohm** [comment]
Can you please share the script you tried?

**Comment by StefanPofahl** [comment]
Thank you for the question! :-)

https://github.com/JuliaEarth/GeoStats.jl
Below is a quick preview of the high-level API:
`using GeoStats`
`using Plots`
`[...]`
`# plot the solution`
`contourf(sol)`

Regards,

Stefan

**Comment by juliohm** [comment]
Oh it is an issue with the copy/paste in GitHub. The CSV table in the README should contain TAB characters. When I copied/pasted the example GitHub replaced TAB with white spaces:

```julia
using CSV
using Tables

julia> t = CSV.File("data.csv")

julia> Tables.columnnames(t)
4-element Vector{Symbol}:
 Symbol("   x")
 Symbol("    y")
 Symbol("       station")
 Symbol("        precip")
```

I will fix the example, thanks for reporting it.

Meanwhile, you can use the example in the docs, which is the same data but constructed directly inside Julia isntead of in a CSV file: https://juliaearth.github.io/GeoStats.jl/stable/index.html#Quick-example

**Comment by juliohm** [comment]
Fixed on master.

**Comment by StefanPofahl** [comment]
What I tried to figure out, what is needed, what is wrong was the following script:
`using CSV, DataFrames`
`ExampleOutputDF = DataFrame(rand(10,10), :auto)`
`CSV.write("ExampleOutputFile.csv", ExampleOutputDF)`
But this was not enough.
Meanwhile I figured out, that a textfile without blanks,
works fine as well.
Thank you very much for the fast response & help :-)

**Comment by juliohm** [comment]
I removed the example from the README to favor the examples in the docs. The README tends to get outdated with time.
