### ISSUE TITLE
Compositional kriging

### ISSUE THREAD

**Issue by stevetyson** [JuliaEarth/GeoStats.jl#232]
Is anyone working on, or thinking about working on, compositional kriging in GeoStats? ... or maybe its already hiding in there and I haven't found it yet :)

**Comment by juliohm** [comment]
It is already implemented. You need to store your compositional data with CoDa.jl and everything should work. We took a more general approach with Hilbert spaces so you can use custom spaces besides Aitchison's space:

https://youtu.be/aQSlPDzqGPY

You can also watch a seminar I gave this year where this feature was useful:

https://youtu.be/uV-byTe4XtU

If you have additional questions, feel free to ask in our community channel:

https://juliaearth.github.io/GeoStats.jl/stable/about/community.html

**Comment by stevetyson** [comment]
Wow! Thanks for the super-quick response. I will try it as soon as I can
