### ISSUE TITLE
Plotting broken in the docs

### ISSUE THREAD

**Issue by Vilin97** [JuliaEarth/GeoStats.jl#244]
It seems that plotting in the [docs](https://juliaearth.github.io/GeoStats.jl/v0.7/plotting.html) is currently broken. 

![image](https://user-images.githubusercontent.com/17322558/218286669-cc34e9fb-a804-4d36-b052-700195b01241.png)

**Comment by juliohm** [comment]
@Vilin97 this docs are for GeoStats.jl v0.7. We are on GeoStats.jl v0.37 already.
