### ISSUE TITLE
Inhomogeneous Poisson process

### ISSUE THREAD

**Issue by ErickChacon** [JuliaEarth/GeoStats.jl#264]
Is there an implementation of an inhomogeneous Poisson process somewhere on `GeoStats.jl` framework or not at all? It would be nice to have full features for this type of process given that is more commonly used for modelling. It would be nice to have:

- Implementation of an inhomogeneous Poisson process where lambda can be:
  - a function (the more general case),
  - a cartesiangrid (where lambda is asummed to be constant inside each cell),
  - another stochastic process (to represent a double stochatic Poisson process).
- Implementation of other type of Poisson processes:
  - Inhibition Poisson process,
  - Clustered Poisson process.
- Sampling could be achieved using `rejecting sampling` (to start with, not sure about more efficient approaches).

Any interest on this?

**Comment by juliohm** [comment]
@ErickChacon I am closing the issue now that we have the inhomogeneous Poisson process working. Feel free to continue working on the other processes you listed above.
