### ISSUE TITLE
Port rotation definitions to Rotations.jl

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/GeoStats.jl#265]
We migrated from ReferenceFrameRotations.jl to Rotations.jl in Meshes.jl, but there are still 3 rotation types defined in GeoStatsBase.jl that rely on the former package. We need to update the rotation definition in terms of the new active rotation types from Rotations.jl.

@hyrodium do you have some time to help port the following definitions?

https://github.com/JuliaEarth/GeoStatsBase.jl/blob/44233f036144835761c61ca346bb9ce871cb498b/src/rotations.jl#L5-L38

If you can write the new definitions here in the issue we can prepare the PR.

**Comment by juliohm** [comment]
@fnaghetini cc'ing you here FYI.

**Comment by juliohm** [comment]
@hyrodium can you please confirm the corresponding type in Rotations.jl that can be used to replace

`EulerAngles(alpha, beta, gamma, :ZYX)`

from ReferenceFrameRotations.jl? Can we just replace it with

`RotZYX(-alpha, -beta, -gamma)`?

**Comment by hyrodium** [comment]
Sorry for the late reply.

> Can we just replace it with `RotZYX(-alpha, -beta, -gamma)`?

No, it should be `RotZYX(-gamma, -beta, -alpha)`.

```julia
julia> using Rotations, ReferenceFrameRotations

julia> RotXYZ(-3,-2,-1)
3×3 RotXYZ{Float64} with indices SOneTo(3)×SOneTo(3)(-3.0, -2.0, -1.0):
 -0.224845  -0.350175  -0.909297
  0.902382  -0.426918  -0.0587266
 -0.36763   -0.833738   0.411982

julia> angle_to_dcm(EulerAngles(1, 2, 3, :ZYX))
DCM{Float64}:
 -0.224845  -0.350175  -0.909297
  0.902382  -0.426918  -0.0587266
 -0.36763   -0.833738   0.411982
```

**Comment by juliohm** [comment]
Fixed by https://github.com/JuliaEarth/GeoStatsBase.jl/commit/8265dfac0db5b83eda10d1882f15841c2b196bcf

**Comment by hyrodium** [comment]
Great!🚀
