### ISSUE TITLE
Running in Python

### ISSUE THREAD

**Issue by cgotelli** [JuliaEarth/GeoStats.jl#266]
Hello! 
I have been trying to run the Image Quilting API function "IQ" from [this article](https://agupubs.onlinelibrary.wiley.com/doi/epdf/10.1029/2019JF005245) in Python with PyJulia. However, I can't manage to do it. Have you ever used this package to call GeoStats? So far I have been using [this thread](https://discourse.julialang.org/t/using-a-function-in-pyjulia/49330/4) as guide and the example of Rita_Paz is running on my PC, so I guess it should run :sweat_smile:. Nevertheless, as I am super new to Julia, I am getting errors like the following: 
```raw
ImportError: <PyCall.jlwrap (in a Julia function called from Python)
JULIA: LoadError: UndefVarError: `CartesianGrid` not defined
```
Can you please help me with this issue?

Thank you very much in advance!

Clemente

**Comment by juliohm** [comment]
Hi Clemente, the issue tracker is for issues with the Julia project. Try to
ask in other  forums for help with Python.

Em seg., 5 de jun. de 2023 12:31, Clemente Gotelli ***@***.***>
escreveu:
