### ISSUE TITLE
Possible bug with MultiPoint and viewer

### ISSUE THREAD

**Issue by luschiro** [JuliaEarth/GeoStats.jl#298]
Running into an error while trying to plot a MultiPoint3 geometry/data with `viewer`.
Original data (`dom_comminution`) plots normally and has `Point` geometry. Tranformations made are as follows:

```
begin
	# creating BWI
	BWI = @chain dom_comminution begin
		@transform(:BWI = 49.0 / ((:A^0.23) * (:M^0.82) * ((10.0/:P80^.5) - (10.0/:F80^.5))) )
	end

	# quantiles
	BWIq1 = quantile(BWI.BWI, .25)
	BWIq3 = quantile(BWI.BWI, .75)

	# BWI classifier
	BWI_classifier = function (x)
		if x > BWIq3
			return "high_BWI"
		elseif x < BWIq1
			return "low_BWI"
		else 
			return "intermediate_BWI"
		end
	end

	# final chain
	BWI_classes = @chain BWI begin
		@transform(:BWI_class = BWI_classifier(:BWI))
		@groupby(:BWI_class)
		@combine(:Si_mean = mean(:Si_ppm))
	end
end
```

* **Error**
![image](https://github.com/JuliaEarth/GeoStats.jl/assets/56177321/9a65fbcf-13ce-48d6-81d5-407e344a9c32)

* original (`dom_comminution.jld2`) and transformed (`BWI_classes.jld2`) data - [issue_geostats.zip](https://github.com/JuliaEarth/GeoStats.jl/files/12480549/issue_geostats.zip)

**Comment by luschiro** [comment]
versioninfo()
```
Julia Version 1.9.2
Commit e4ee485e90 (2023-07-05 09:39 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 16 × AMD Ryzen 7 4800H with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver2)
  Threads: 1 on 16 virtual cores
```

---
Pkg.status()

`[c3e4b0f8] Pluto v0.19.27`

**Comment by juliohm** [comment]
Thank you for reporting the issue @luschiro , it should be fixed now in the master branch. The fix will be included in the next release, which is coming with lots of improvements :)
