### ISSUE TITLE
Difference in computation time depending on MetricBall parameters

### ISSUE THREAD

**Issue by hameye** [JuliaEarth/GeoStats.jl#325]
Hi there, I noticed a quite big difference in computation time in Kriging algorithm when changing the MetricBall parameters in the neighborhood_model.
When using `neighborhood_model = Meshes.MetricBall(3000)`, the algorithm takes about 7s and when using `neighborhood_model = Meshes.MetricBall([3000, 3000, 20])`, the algorithm takes about 25s. 
Looking at the code, this behaviour seems related to the use of two different distances from Distances.jl (Euclidean and Mahalanobis). 

Sorry if this issue has to be asked elsewhere, I did not really know where to notice this behaviour since it is coming from Meshes.jl package and directly due to Distances.jl.

**Comment by juliohm** [comment]
Can you please confirm that you're using the latest version? We moved the
Kriging routine to the Interpolate and InterpolateNeighbors transforms.

Also, please share a MWE so that we can time the code as well.

Em seg., 6 de nov. de 2023 05:38, hameye ***@***.***>
escreveu:

**Comment by hameye** [comment]
@juliohm 
I am using GeoStats  v0.46.0. 
Here is a MWE (I copy-pasted from the data found in [Geospatial Data Science with Julia](https://juliaearth.github.io/geospatial-data-science-with-julia/), great book thank you for sharing it !). I know the results are no good but this gives a good idea of the time difference between the two types of neighborhood I was mentioning.

```julia
using GeoStats
using CSV

url = "https://zenodo.org/record/7051975/files/drillholes.csv?download=1"
dtable = GeoStats.georef(CSV.File(download(url)), ("X", "Y", "Z"));
selectholeid = GeoStats.Select("HOLEID")
selectgrades = GeoStats.Select("Cu ppm" => "Cu",) → 
    GeoStats.Functional(x -> 1e-4*x*u"percent") # 1 ppm = 1e-4 percent

dclean = selectholeid ⊔ selectgrades
dtable = dclean(dtable)
bbox = GeoStats.boundingbox(dtable.geometry)
bsize = (12.5, 12.5, 12.5)
grid = GeoStats.CartesianGrid(extrema(bbox)..., bsize)

problem = GeoStats.EstimationProblem(dtable, grid, :Cu)
cov = NuggetEffect() + 6 * SphericalVariogram()

neighborhood_model_1 = Meshes.MetricBall( [3000, 3000, 20] )
neighborhood_model_2 = Meshes.MetricBall(3000)

model = GeoStats.Kriging(cov)
interp = dtable |> GeoStats.InterpolateNeighbors(problem.domain, model, minneighbors=1, maxneighbors=5, neighborhood=neighborhood_model)

```

neighborhood_model_1 leads to an execution time of interp of 8.5 s and neighborhood_model_2 lead to an execution time of interp of 3.6 s

**Comment by juliohm** [comment]
Thank you! Glad the book is helpful. If you are familiar with benchmarking
code in Julia, feel free to share a flame graph of the parts that are
taking more time. We are not using multithreading yet, but it is in the
roadmap.

The packages BenchmarkUtils.jl and TimerOutpuputs.jl may be useful. Also
VSCode has a profiler that you can run with @profile if I'm not mistaken.

Any additional hint on where are the bottlenecks will help us speed things
up more quickly.

Em seg., 6 de nov. de 2023 11:46, hameye ***@***.***>
escreveu:

**Comment by hameye** [comment]
Yes, I am using ProfileView.jl, this is what lead me to find out the issue seems to be related deeper to the NearestNeighbors.jl where there is a difference in computation time between kd tree and ball tree and seems to be due to the evaluate function from Distances.hl

Here is the graph using the isotropic MetricBall
![Screenshot from 2023-11-06 16-21-01](https://github.com/JuliaEarth/GeoStats.jl/assets/57682091/b15ec9ef-ce4b-43d3-81ce-1c3e477bb44e)
Here is the graph using the anisotropic MetricBall
![Screenshot from 2023-11-06 16-21-26](https://github.com/JuliaEarth/GeoStats.jl/assets/57682091/5498cd0b-12c7-4f83-9672-e4f6fc0b1b4d)

**Comment by juliohm** [comment]
By quickly looking into the code, the difference in computation time is expected. The Euclidean distance (default) requires less CPU instructions than the Mahalanobis distance. Additionaly, there is the KDTree versus BallTree difference in NearestNeighbors.jl In order to reduce the time gap, one would need to improve Distances.jl and NearestNeighbors.jl, so I will close this issue here, which is not directly related to our stack.

We still have plans to optimize the code further with multiple threads and other optimizations, but that is something that we plan to address later after other priorities.

**Comment by juliohm** [comment]
Feel free to continue the conversation in our Zulip channel.
