### ISSUE TITLE
Multi-output / Multi-task Processes

### ISSUE THREAD

**Issue by markmbaum** [JuliaEarth/GeoStats.jl#375]
I'm curious if there is any support for multi-output processes, in particular Gaussian processes. I'm interested in simulating observations of several quantities in two-dimensional space, where each quantity is spatially correlated and there is correlation between the quantities.

**Comment by juliohm** [comment]
Yes, we support 2D as well as 3D  simulation. See some examples in the docs: https://juliaearth.github.io/GeoStatsDocs/stable/random/fields.html

**Comment by markmbaum** [comment]
Thanks Julio. I'm a little confused about the field simulation examples. Looking at this one:

`rand(process, domain, ["a" => Float64, "b" => Float64])`

The relationship between the `data` arguments `"a"` and `"b"` are not clear to me. It seems like `"a"` and `"b"` are independent realizations of the same process, but returned with different names/labels? I'm also not entirely sure why their numeric types need to be specified explicitly.

Sorry to bother. Happy to contribute to the docs if it's helpful.

**Comment by juliohm** [comment]
Hi @markmbaum, we are happy help with usage questions in our Zulip channels. We use GitHub is for issues and bug fixes.

The variables are simulated with a pre-allocated memory block, and that is why we need the types. Sometimes the types can be inferred from data (conditional simulation), which is passed as a geotable.
