### ISSUE TITLE
Documentation Versioning

### ISSUE THREAD

**Issue by sonofwatt84** [JuliaEarth/GeoStats.jl#394]
Is there any reason documentation for older (before current) versions of GeoStats.jl are not maintained?  It's rather disappointing to find the documentation for the version you've been working with has simply disappeared.

**Comment by juliohm** [comment]
We simply don't have the time and people to maintain old docs. The
framework is evolving too much and old docs look very different. Which
version are you using?

Em seg., 5 de fev. de 2024 21:29, Peter Watson ***@***.***>
escreveu:

**Comment by juliohm** [comment]
The other issue that motivated us to remove old versions of the docs is that the plots were filling up all the space in the GitHub repository. We moved the docs to a separate repository, but it wasn't enough. GitHub imposes a size limit in deploy Actions.
