### ISSUE TITLE
Introduce the notion of volumetric measurements

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/GeoStats.jl#40]
The Kriging-based solvers implemented so far assume that the measurements have a fixed volume. This assumption is quite strong, and we need to generalize the implementations to achieve block Kriging.

First we need to generalize the spatial object types to include volumetric information. If anyone has suggestions on efficient data structures for representing spatial domains with volumes, please feel free to share. I am tempted to continue with types a la VTK. After that, we can start working on the Kriging-based solvers to incorporate these modifications.

**Comment by exepulveda** [comment]
We could introduce the concept of Support. What we have at the moment is "Point Support" or at least is assumed. One idea may be giving to the estimation domain a support feature. In case of 2D the support is a rectangle with a discretisation. For 3D is simply a box with also a discretisation. Later we can also extend this for samples, in case someone wants to make estimations of large support using data at small support.

**Comment by juliohm** [comment]
We can go one step further and support general finite element meshes. We have the foundations in place, now we just need to formalize an API for accessing individual elements of the mesh (which have a full geometric description). An initial draft of this API lives in Meshes.jl: https://github.com/JuliaGeometry/Meshes.jl It is incomplete, and I am trying to fix other issues before we jump into this major effort. It is an exciting one though.

**Comment by exepulveda** [comment]
This issue is very important to address if we want to make this project usable in mining. Block kriging is one of the geostatistical methods most used in mining. Not having this option forces user to use alternative software.

**Comment by juliohm** [comment]
Fully agree. By the end of the month we will have a new release of the project with mesh support, and then we will be able to start working on block Kriging and other more advanced approaches.

**Comment by juliohm** [comment]
We now have full support to general meshes. Closing the issue, and we can open a new one for block Kriging specifically.
