### ISSUE TITLE
Allow `georef(x, ::Symbol)`

### ISSUE THREAD

**Issue by pdeffebach** [JuliaEarth/GeoStats.jl#425]
Because a `GeoTable` is not mutable, I frequently convert a `GeoTable` back and forth from a `DataFrame`. But using `georef` is not very user-friendly. 

I use DataFramesMeta.jl pretty heavily, so I avoid `GeoStats.@transform` etc. 

If `geometry` exists in the DataFrame, you get 

```
> GeoStats.georef(zones_geo, zones_geo.geometry)
Error showing value of type GeoTables.GeoTable{GeoTables.GeoTable{DataFrame}}:
ERROR: The number of columns in the header (9) must be equal to that of the table (8).
Stacktrace:
```

So I often have to do something like 

```
@chain df begin 
        @aside geometry = _.geometry
        @select Not(:geometry)
        GeoStats.georef(_, geometry)
end
```

which is kind of annoying. 

Would be cool to do `GeoStats.georef(_, :geometry)` to refer to the `geometry` column.

**Comment by juliohm** [comment]
I believe you can already pass the DataFrame with geometry column to the
GeoTable constructor. Can you please confirm?

Em qua., 8 de mai. de 2024, 12:22, pdeffebach ***@***.***>
escreveu:

**Comment by pdeffebach** [comment]
Indeed. I didn't realize I could use the constructor directly.

To be clear, does `GeoTable` work similar to `DataFrame` and just falls back on `Tables.jl` checks?

**Comment by juliohm** [comment]
It currently assumes the existence of a geometry column. It will throw
otherwise. Is that the question? There is also a georef method with symbols
of coordinate names.

Em qua., 8 de mai. de 2024, 12:45, pdeffebach ***@***.***>
escreveu:

**Comment by pdeffebach** [comment]
I just mean, it's not an internal constructor? It really is meant to be used on a wide variety of inputs? And yes, also assuming the `:geometry` column.

**Comment by juliohm** [comment]
Yes, this constructor accepts any table a la Tables.jl. It is the only
constructor intended for end users. The georef function is recommended
otherwise.

Em qua., 8 de mai. de 2024, 12:49, pdeffebach ***@***.***>
escreveu:

**Comment by pdeffebach** [comment]
Thank you! Closing this.
