### ISSUE TITLE
Idea / Question: Kriging under constraints

### ISSUE THREAD

**Issue by StreetLevel** [JuliaEarth/GeoStats.jl#426]
Hello,

first of all `Geostats.jl` is a great package. Thank you for providing such a great package to the Julia community.

After I played around with it for a little while, I noticed that by Kriging interpolation you can easily generate values for parameters which are physically unfeasable.
Therefore my question would be if I can place constraints on a Kriging interpolation such that a paramter is
 
```julia
x::Float64-> x > 0.0 && x < 1.0
```

is below and above certain thresholds and, in addition, maybe put constraints on a collection of parameters

```julia

x::AbstractVector-> sum(x) > 0.0 && sum(x) < 1.0
```

such that `modelers knowledge` can be introduced into the Kriging interpolation?

Is there a way to do this or is something like that planned?

Or is this even not possible?

Thank in advance.

Greetz max

**Comment by juliohm** [comment]
Thank you for the kind words. It is lovely to see the community growing and
providing feedback.

It is certainly possible to impose constraints given that Kriging is a
well-defined optimization problem with specific constraints (unbiasedness).
If you want to contribute such model to GeoStatsModels.jl we can help with
a list of references.

Are you familiar with convex optimization? Kriging is a convex optimization
problem that has been optimized to cache the linear solutions at each
location. We can implement similar tweaks to scale different linear
constraints.

Em dom., 12 de mai. de 2024, 07:59, Max Bittens ***@***.***>
escreveu:

**Comment by juliohm** [comment]
Also notice that the constraints you have in mind are called compositional
constraints. Our Kriging solvers can interpolate any object in a Hilbert
space, including compositions from CoDa.jl

Perhaps that is all you need?

Em dom., 12 de mai. de 2024, 08:34, Júlio Hoffimann <
***@***.***> escreveu:

**Comment by juliohm** [comment]
@StreetLevel feel free to continue the discussion in our Zulip channel.
