### ISSUE TITLE
Simulation involving objects of different parametric dimension

### ISSUE THREAD

**Issue by PaulMatlashewski** [JuliaEarth/GeoStats.jl#52]
A very nice feature I would love to see is the ability to simulate variables on spatial domains that are much smaller than the domain of the input data. For example, I am often only interested in values along a fixed cross-section while my data is spread over 3 dimensions.

This works nicely with estimation problems, but I'm not sure if it is feasible for conditional simulation problems.

**Comment by juliohm** [comment]
Thank you @PaulMatlashewski , can you elaborate on the issue a bit more? I understand you are interested in simulating a cross-section of a 3D volume using 3D neighbourhood information to constrain the cross-section values, correct?

**Comment by PaulMatlashewski** [comment]
Yes, exactly. The image below shows what currently happens when I attempt this (this is the average of many simulations). The data values are being mapped to the cross-section grid and simulated from there.

I would want the points where the drillhole object intersects the plane to be perfectly constrained, and the data off-section to constrain the simulation based on the distance away from the section

![simulation_problem](https://user-images.githubusercontent.com/13931255/74194130-881b5580-4c0d-11ea-9fbc-23998aff5476.png)

**Comment by juliohm** [comment]
That is indeed a very nice feature request, thank you. We should keep it in mind as we work on the next major release of the project. There is a lot of work to be done regarding this generalisation with multiple dimensions on the same problem definition, but it is certainly possible after we address some milestones: https://github.com/JuliaEarth/GeoStats.jl/projects

**Comment by juliohm** [comment]
Hi @PaulMatlashewski , I think we have this feature now. You should be able to create domains of different parametric dimension given that they live in the same embedding dimension. Please let me know if you have questions. We are on Gitter or Zulip to discuss use cases.

**Comment by PaulMatlashewski** [comment]
Wonderful! Thanks @juliohm.
