### ISSUE TITLE
Allow parallelepiped shaped blocks for spatial partition

### ISSUE THREAD

**Issue by BrenoWSRCa** [JuliaEarth/GeoStats.jl#55]
There would be nice to have the BlockPartitioner a generalized to allow blocks of different side sizes. It should generalize the BlockCrossValidation method as well.

**Comment by juliohm** [comment]
Fixed in https://github.com/JuliaEarth/GeoStatsBase.jl/commit/bd2dad9bebf944a22a9c773783db6aed14045e1b
