### ISSUE TITLE
`no method matching LinearPath()` error with latest update (v0.11.7)

### ISSUE THREAD

**Issue by briochemc** [JuliaEarth/GeoStats.jl#65]
With the unupdated packages like InverseDistanceWeighting.jl, [the quick example of the documentation](https://juliaearth.github.io/GeoStats.jl/stable/#Quick-example-1) throws at

```julia
julia> # solve the problem
       solution = solve(problem, solver)
ERROR: MethodError: no method matching LinearPath()
Closest candidates are:
  LinearPath(::D) where D<:AbstractDomain at /Users/benoitpasquier/.julia/packages/GeoStatsBase/gtoIM/src/paths/linear.jl:11
Stacktrace:
[1] preprocess(problem::EstimationProblem{PointSetData{Float64,2},RegularGrid{Float64,2},NearestMapper}, solver::Kriging)
  @ KrigingEstimators ~/.julia/packages/KrigingEstimators/RONev/src/solvers/kriging.jl:124

[2] solve(problem::EstimationProblem{PointSetData{Float64,2},RegularGrid{Float64,2},NearestMapper}, solver::Kriging)
  @ KrigingEstimators ~/.julia/packages/KrigingEstimators/RONev/src/solvers/kriging.jl:141

[3] top-level scope
  @ REPL[9]:2
```

I think this is because the changes in GeoStatsBase.jl are *necessary* for the latest version of KrigingEstimators.jl. So maybe the compat needs to strictly impose GeoStatsBase v0.10 instead of currently allowing older versions?

**Comment by juliohm** [comment]
This is my fault. I've had a misconception about the compat bounds section of the package manager. I am triggering a cycle of releases right away to fix the issue.

**Comment by juliohm** [comment]
I've registered the patch releases, they should be available in a few minutes:

https://github.com/JuliaRegistries/General/pull/16080
https://github.com/JuliaRegistries/General/pull/16081
https://github.com/JuliaRegistries/General/pull/16082
https://github.com/JuliaRegistries/General/pull/16083
https://github.com/JuliaRegistries/General/pull/16084

Thanks for sharing the issue, and sorry for the noise.

**Comment by briochemc** [comment]
No need to be sorry! You're more than welcome! I only noticed this because I had those packages (like InverseDistanceWeighting) in my main environment and was trying to play with the updated GeoStats.jl and I just thought you'd want to know about this 😄
