### ISSUE TITLE
Minor improvements to variograms

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/GeoStats.jl#73]
We need a few minor improvements to the variogram types:

- [ ] The empirical variogram plot could have a right vertical axis for the bin counts, or alternatively, we could show the counts in the markers directly.
- [x] The theoretical variogram plot could follow the syntax of a normal Julia function, i.e. `plot(g, 0, maxlag)` as opposed to `plot(g, maxlag=maxlag)`.
- [x] The text representation of empirical variograms could be improved, it is not clear what is being presented inside the parenthesis.

This issue is good for first-time contributors.

**Comment by exepulveda** [comment]
I can take this task 👍🏽 
Could you give me indications where to start? I mean the key source code.

**Comment by juliohm** [comment]
Of course :heart: 

Let's start with the third box because it is easier to fix without any knowledge about the Julia's plotting machinery. These two methods implement the "display" behavior of empirical variograms: https://github.com/JuliaEarth/Variography.jl/blob/db5f86f63ef8b3ce4a5451474703f87f6a2ff844/src/empirical.jl#L143-L156

The first method is used as a short version when we have for example a vector of empirical variograms. In this case each entry of the vector will display as `EmpiricalVariogram`. The second method is a full display when we just display a single variogram, it currently prints the distance used, the min/max of abcissa and ordinate and the number of pairs. We could replace the min/max of abscissa and ordinate by something more useful to the user. Perhaps the maximum lag and number of lags for example.

**Comment by juliohm** [comment]
@exepulveda BTW you can now create the branches for the PRs in the JuliaEarth/Variography.jl repo directly. No need to fork as you are part of the org already.

**Comment by juliohm** [comment]
This issue is solved, except for the first item, which is currently not possible because Plots.jl does not support right vertical axis in plot recipes. I will close the issue for now.
