### ISSUE TITLE
Improve plot recipe for spatial data

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/GeoStats.jl#74]
Currently we plot spatial data with `plot(d, variables=[:a,:b,...])` where `:a,:b,...` are the variable names. We should simplify the command to `plot(d, (:a,:b,...))`.

Additionally, the code snippet that extracts the vector with values can be simplified: https://github.com/JuliaEarth/GeoStatsBase.jl/blob/83c515847ba6cc333a0c03c7f2e3882f1a2e7251/src/plotrecipes/data.jl#L21-L28 

1. It shouldn't use the `isvalid` function (deprecated). We could simply use Julia built-in functions to replace `missing` by `NaN`.
2. It should also handle `CategoricalArrays.jl` and convert the categories (e.g. strings) by factors (integers) before plotting.

@LakshyaKhatri given our recent discussions around plots, this is an issue that you could be interested in fixing. Please let me know if you would like to give it a try :)

**Comment by LakshyaKhatri** [comment]
Hello @juliohm, I will work on this issue as soon as I complete my current PR at plots. Unfortunately, it is taking longer than expected :(

**Comment by juliohm** [comment]
Whenever you find the time @LakshyaKhatri :) I know well how Plots.jl PRs can take a while...

**Comment by LakshyaKhatri** [comment]
Hello @juliohm, I am starting to work on this repo. I think I can handle two repos at the same time! :100:

**Comment by juliohm** [comment]
That is great @LakshyaKhatri , please let me know if you have any questions.

**Comment by LakshyaKhatri** [comment]
Hello @juliohm, I just looked into the issue. Seems like `GeoStats.jl` is just an abstraction. Do I have to edit everything in `GeoStatsBase.jl` if I am not wrong?

**Comment by juliohm** [comment]
You are correct @LakshyaKhatri , GeoStats.jl is just an umbrella package, the actual functionality lives in submodules in separate repositories. GeoStatsBase.jl contains the plot recipes mentioned in the issue. 👍

**Comment by juliohm** [comment]
@LakshyaKhatri I've marked all open issues related to plotting with the `visualization` label in case you are interested in addressing other issues after this one you are currently working on :)

**Comment by LakshyaKhatri** [comment]
@juliohm, this might be a bit disappointing:

I won't be able to contribute since I have to prepare for the upcoming interviews. :'(
I will complete my currently opened PRs.

**Comment by juliohm** [comment]
It is not disappointing at all. I can only acknowledge your contributions @LakshyaKhatri :heart: it is been really fun to work with you on this and other related projects. I hope everything goes well with the interviews, wishing you good luck!

Let me know if you need recommendations, I'd be happy to write something about your contributions to open source in Julia.

**Comment by LakshyaKhatri** [comment]
Thanks a lot for such a kind response @juliohm. Really means a lot to me :heart: :raised_hands:
