### ISSUE TITLE
KrigingSolver is indexing pdomain instead pdata for searching

### ISSUE THREAD

**Issue by exepulveda** [JuliaEarth/GeoStats.jl#76]
In the preprocess function, pdomain is used to index the neighbours, which conceptualy is not correct.
kriging should index pdata and search k neighbours from pdata instead with no need of masking previously estimated locations.

Currently, it is not clear to me but it seems with datamap Kriging solver is trying to map locations in pdata to pdomain and mask those mapped locations as estimated. This may give different results because pdomain locations may not necessarily match to pdata mapped location  and the covariances may not be the right.

I will propose a fix for this.

**Comment by juliohm** [comment]
Fixed by https://github.com/JuliaEarth/KrigingEstimators.jl/pull/16
