### ISSUE TITLE
Implementing rotations that are used in mining applications

### ISSUE THREAD

**Issue by exepulveda** [JuliaEarth/GeoStats.jl#96]
In mining applications there are several different rotation systems. For example, GSLIB and Vulcan conventions. It could be great to add those rotation systems in order to correctly define the distances based on them.

**Comment by juliohm** [comment]
FYI, we have existing implementations of coordinate transformations, including rotations, that we can use here if necessary: https://github.com/JuliaGeometry/CoordinateTransformations.jl

**Comment by exepulveda** [comment]
Here is the [GSLIB angle conventions](http://geostatisticslessons.com/lessons/anglespecification).
Basically, the rotation is defined by specifying azimuth, dip and plunge. Azimuth is measured from north clockwise. We already have Euler transforms, so we could have angles transform functions to feed Ellipsoidal metric.

Do you think that we could have a dedicated subpackage for mining applications? GeoMining, for example. I'm in the process of writing a notebook that shows how to write JuliaEarth code that is equivalent to, for example, GSLIB or Vulcan.

**Comment by juliohm** [comment]
I think the most general and flexible approach would be for us to introduce some transformation types in GeoStatsBase.jl based on the transformation types of CoordinatesTransformations.jl and then feed instances of these types to other parts of the framework when needed. For example, we could have a `EulerRotation` and a `TaitBryanRotation` following the terminology in `geostatisticslessons.com` Makes sense?

> Do you think that we could have a dedicated subpackage for mining applications? GeoMining, for example. I'm in the process of writing a notebook that shows how to write JuliaEarth code that is equivalent to, for example, GSLIB or Vulcan.

In the Julia community, you will notice that we always attempt to generalize problems and provide implementations that are flexible enough for specific applications. In my opinion, we have an advantage when we unite efforts on a single codebase that can be used across domains (e.g. climate sciences, mining, oil & gas). The mining industry has a lot to contribute to other domains, and, as you know, most of this knowledge is inaccessible partially because of historical community splits.

**Comment by rmcaixeta** [comment]
I think that a flexible way to deal with that would be adding an extra kwarg to Ellipsoidal function to inform the rotation axis order (currently fixed to Z,X,Y). Then would be possible to match more easily to any rotation convention and build "recipes" (where clockwise/counterclockwise specific rules can be handled). With that one we can get to GSLIB this way, for example:

```julia
function GSLIB(ang1,ang2,ang3,a_hmax,a_hmin,a_vert)
	Ellipsoidal([a_hmin,a_hmax,a_vert], [deg2rad(-ang1),deg2rad(ang2),deg2rad(ang3)])
end

ang1,ang2,ang3 = [45.,-45.,90.]
a_hmax,a_hmin,a_vert = [50.,37.5,25.]
rot = GSLIB(ang1,ang2,ang3,a_hmax,a_hmin,a_vert)

ngt,cc = [0.1,0.9]
vario = SphericalVariogram(sill=ngt+cc, nugget=ngt, distance=rot)

#GSLIB notation
#1    0.1                     -nst, nugget effect
#1    0.9  45.0   -45.0   90.0    -it,cc,ang1,ang2,ang3
#         50.0   37.5  25.0    -a_hmax, a_hmin, a_vert
```

But for other conventions the extra kwarg would really help (eg. Z,X,Z is getting "popular" in some areas). I can help with that if it's no one started yet and you guys think this approach sounds good.
 
I like the idea of having it as quaternions too. Would be easier to "average" ellipsoids for those interested. But I never went deep on that, don't know how it'd be the best way to apply it. Reading the discussion of your link, it seems to be quite fixed to some rotation conventions. Maybe after having the Ellipsoidal working for different conventions, there's some way to convert the semiaxes orthogonal vectors to the desired quaternion package/convention.

**Comment by juliohm** [comment]
That would be lovely @rmcaixeta . So the idea is to add a `order` kwarg or similar to the `Ellipsoidal` constructor that would store a given convention like `order=(:z,:x,:y)` or maybe `order=:Euler` and then construct the appropriate rotation matrix internally. Is that correct? I think this a very reasonable solution while we brainstorm a more flexible set of tools for rotations in the project. :+1:

**Comment by rmcaixeta** [comment]
Correct. That way we can match any convention

**Comment by juliohm** [comment]
Thanks for proposing the changes. Please feel free to draft a PR and we can continue the discussion over there. Also we could take this opportunity to convert the matrix inside Ellispsoidal to a static matrix `SMatrix`. That will certainly speed things up.

**Comment by exepulveda** [comment]
I like the idea and it is what I'm current working on.

Apparently the correct rotation to account for the reduction of the distances in the axis should be:

```
function GSLIB(ang1, ang2, ang3, a_hmax, a_hmin, a_vert)
	Ellipsoidal([1.0, a_hmin/a_hmax,a_vert/a_hmax], [deg2rad(-ang1),deg2rad(ang2),deg2rad(ang3)])
end
```

> 
> ```julia
> function GSLIB(ang1,ang2,ang3,a_hmax,a_hmin,a_vert)
> 	Ellipsoidal([a_hmin,a_hmax,a_vert], [deg2rad(-ang1),deg2rad(ang2),deg2rad(ang3)])
> end
> 
> ang1,ang2,ang3 = [45.,-45.,90.]
> a_hmax,a_hmin,a_vert = [50.,37.5,25.]
> rot = GSLIB(ang1,ang2,ang3,a_hmax,a_hmin,a_vert)
> 
> ngt,cc = [0.1,0.9]
> vario = SphericalVariogram(sill=ngt+cc, nugget=ngt, distance=rot)
> 
> #GSLIB notation
> #1    0.1                     -nst, nugget effect
> #1    0.9  45.0   -45.0   90.0    -it,cc,ang1,ang2,ang3
> #         50.0   37.5  25.0    -a_hmax, a_hmin, a_vert
> ```
> 
> But for other conventions the extra kwarg would really help (eg. Z,X,Z is getting "popular" in some areas). I can help with that if no one started yet and you guys think this approach sounds good.
> 
> I like the idea of having it as quaternions too. Would be easier to "average" ellipsoids for those interested. But I never went deep on that, don't know how it'd be the best way to apply it. Reading the discussion of your link, it seems to be quite fixed to some rotation conventions. Maybe after having the Ellipsoidal working for different conventions, there's some way to convert the semiaxes orthogonal vectors to the desired quaternion package/convention.

**Comment by rmcaixeta** [comment]
Hi @exepulveda

Thanks. I did not validate fully that GSLIB function, just for 1-2 GSLIB vmodel cases. Also depends on what's the range you're using in the variogram function (max, min, vert, 1.0 etc)

I started doing that, but did not validate any of the results yet:
https://github.com/rmcaixeta/GeoStatsBase.jl/commit/5d4410fda7781cebb0884e7f6a09a6b71deb067e

It would work like that below:

```julia
rot = Ellipsoidal([a_hmax, a_hmin, a_vert], [ang1, ang2, ang3], order=:GSLIB)
SphericalVariogram(sill=ngt+cc, nugget=ngt, distance=rot)
```

Let me know if you have any suggestion in advance about that. But still need some more time on that before sending a PR

**Comment by exepulveda** [comment]
I like the syntax. Simple and easy to read and understand. I have done some tests with Ellipsoidal, and I could not find any equivalence. In the meantime I'm working with a costumed distance using the same GSLIB source code.

**Comment by exepulveda** [comment]
Hi guys! I have been testing the new rotation function aniso2distance and I could not reproduce the GSLIB rotation matrix so far.
This is the code translated from GSLIB Fortran code to Julia (and properly tested):

```
function setrot(ang1, ang2, ang3, anis1, anis2)
  if ang1 >= 0.0 && ang1 < 270.0
    alpha = deg2rad(90.0 - ang1)
  else
    alpha = deg2rad(450.0 - ang1)
  end

  beta  = -1.0 * deg2rad(ang2)
  theta =        deg2rad(ang3)
    
  sina  = sin(alpha)
  sinb  = sin(beta)
  sint  = sin(theta)
  cosa  = cos(alpha)
  cosb  = cos(beta)
  cost  = cos(theta)
  
  afac1 = 1.0 / max(anis1,eps(1.0))
  afac2 = 1.0 / max(anis2,eps(1.0))

  rotmat = Matrix{Float64}(undef,3,3)

  rotmat[1,1] =       (cosb * cosa)
  rotmat[1,2] =       (cosb * sina)
  rotmat[1,3] =       (-sinb)
  rotmat[2,1] = afac1*(-cost*sina + sint*sinb*cosa)
  rotmat[2,2] = afac1*(cost*cosa + sint*sinb*sina)
  rotmat[2,3] = afac1*( sint * cosb)
  rotmat[3,1] = afac2*(sint*sina + cost*sinb*cosa)
  rotmat[3,2] = afac2*(-sint*cosa + cost*sinb*sina)
  rotmat[3,3] = afac2*(cost * cosb) 
  
  rotmat
end
```
The simplest test is no rotation nor anisotropy:

```
julia> setrot(0.0, 0.0, 0.0, 1.0, 1.0)
3×3 Array{Float64,2}:
  6.12323e-17   1.0          0.0
 -1.0           6.12323e-17  0.0
  0.0          -0.0          1.0
```
The equivalent call to 
```
anidist = aniso2distance([1.0,1.0,1.0], [0.0,0.0,0.0], convention=:GSLIB)
anidist.qmat
3×3 StaticArrays.SArray{Tuple{3,3},Float64,2,9} with indices SOneTo(3)×SOneTo(3):
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0
```

which is not the right rotation. GSLIB convention uses X axis as the east direction. 

If you add azimuth of 30 degress, the rotation, according to aniso2distance, becomes:

```
julia> anidist = aniso2distance([1.0,1.0,1.0], [30.0,0.0,0.0], convention=:GSLIB)
Distances.Mahalanobis{StaticArrays.SArray{Tuple{3,3},Float64,2,9}}([1.0 0.0 0.0; 0.0 1.0 0.0; 0.0 0.0 1.0])

julia> anidist.qmat
3×3 StaticArrays.SArray{Tuple{3,3},Float64,2,9} with indices SOneTo(3)×SOneTo(3):
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0
```

but it should be: 

```
julia> setrot(30.0, 0.0, 0.0, 1.0, 1.0)
3×3 Array{Float64,2}:
  0.5        0.866025  0.0
 -0.866025   0.5       0.0
  0.0       -0.0       1.0
```

**Comment by rmcaixeta** [comment]
Hi @exepulveda 
I'll test your example later today to understand what's going on
The validations I made was using GSLIB vmodel vs GeoStats.jl anisotropic variogram, they were matching perfectly

**Comment by rmcaixeta** [comment]
Just to confirm, I ran again the tests and the anisotropic variograms with `aniso2distance` do match the GSLIB vmodel using a series of different angles and ranges
The issue is that the `qmat` for Mahalanobis is `P'*Λ*P` and what you're seeking is `sqrt.(Λ)*P` (https://github.com/JuliaEarth/GeoStatsBase.jl/blob/master/src/distances.jl)

Another difference is the way I built the rotation matrix for GSLIB. In order to avoid the alpha pre-transformations made in fortran, I only inverted the ranges of x-y in GSLIB case. I think it's just different ways to write the same thing, but it's more similar to the matrix shown in here
http://www.geostatisticslessons.com/lessons/anglespecification

Do you want this matrix for coordinate transformations? Maybe you could duplicate/adapt the aniso2distance function to return `sqrt.(Λ)*P` (or `sqrt.(Λ)*P'` for extrinsic cases), but would need to test if it really works as it is. For GSLIB case, maybe would be necessary to invert 1st and 2nd lines like `sqrt.(Λ)*P[[2,1,3],:]` because of the inversion of x-y

**Comment by exepulveda** [comment]
Quite interesting. I just wonder if Mahalanobis distance, which only stores the Q (qmat) matrix is capable of reproducing the right rotation. Somehow using Q matrix should be enough.

**Comment by exepulveda** [comment]
Another point is that given an azimuth of 30 degrees, it seems the Q matrix is still the Identity, which is correct as there is not differences in the distances when you use rotation if you don't use anisotropy. I think that is the error with my comparison. I need to test with anisotropy and rotation.

**Comment by rmcaixeta** [comment]
Yeah, maybe there's some way depending on whats the purpose. If you need only anisotropic distances, it will help. But I guess that for explicit coordinate transformations and rotations the original rotation matrix will be necessary in the end

**Comment by exepulveda** [comment]
Your are 100% right. They are equivalent. See this test:

```
function sqdist(p1,p2,rotmat)
  dx = p1[1] - p2[1]
  dy = p1[2] - p2[2]
  dz = p1[3] - p2[3]
  sd = 0.0
  for i=1:3
      cont   = rotmat[i,1] * dx + rotmat[i,2] * dy + rotmat[i,3] * dz
      sd = sd + cont * cont
  end
  sd
end

gslibdist(x,y,R) = sqrt(sqdist(x,y,R))

n = 1000
for i=1:n
  for j=1:n
    p1=rand(3)
    p2=rand(3)
    ani1 = rand()*5.0+0.1
    ani2 = rand()*1.0+0.1
    angles = rand(3)*360.0 .- 180.0
    R = setrot(angles...,ani1, ani2)
    gsdist = aniso2distance([1.0,ani1,ani2], angles, convention=:GSLIB)
    d1 = gslibdist(p1,p2,R)
    d2 = gsdist(p1,p2)
    @assert d1 ≈ d2
  end
end
```

Rotations and anisotropy at random. All results OK.

The only missing point is getting a *valid* rotation matrix to be used in the KDTree for example. With this test I can also say that this functionality is correct. Great!!

Thanks for making this nice API.

**Comment by juliohm** [comment]
Thank you all for double checking the rotations. I think it would be nice to expose them in future releases besides the Mahalanobis distance obtained after stretching the axes.

**Comment by juliohm** [comment]
Currently we can already express anisotropic models with the `aniso2distance` function. We can discuss a general rotation API in a future separate issue.
