### ISSUE TITLE
Kriging linear systems are by construction symmetric. We could take advantage of.

### ISSUE THREAD

**Issue by exepulveda** [JuliaEarth/GeoStats.jl#97]
In Simple Kriging, we are doing the right thing, i.e., using the cholesky factorisation.
The same can be done for OK by using LDL' factorisation, that I understand is done by marking the A matrix with Symmetric(A).
This feature can make a little bit faster all the calculations.

**Comment by juliohm** [comment]
You are right, I think Julia needs an explicit call to `Symmetric` to take advantage of the appropriate algorithm. Thanks for raising the issue. Would you like to submit a PR? :)
